# Predicting Division I Men's Basketball Transfer Portal Starters

**Team members:** Aurea McIntosh, Zoe Edelblum, Evie McMahan
**Repository:** https://github.com/eviemcmahan/ds_3001_project_team_6.git

## Setup

Use relative paths and keep the notebook runnable from beginning to end.

In [39]:
from pathlib import Path

DATA_DIR = Path("data")
assert DATA_DIR.is_dir(), "The data directory is missing."

## Load data

In [40]:
# Load data from DATA_DIR.
import pandas as pd

espn_rankings = pd.read_csv(DATA_DIR / "espn_preseason_rankings.csv")
player_stats_2020 = pd.read_csv(DATA_DIR / "player_stats_2020.csv")
player_stats_2021 = pd.read_csv(DATA_DIR / "player_stats_2021.csv")
player_stats_2022 = pd.read_csv(DATA_DIR / "player_stats_2022.csv")
player_stats_2023 = pd.read_csv(DATA_DIR / "player_stats_2023.csv")
player_stats_2024 = pd.read_csv(DATA_DIR / "player_stats_2024.csv")
player_stats_2025 = pd.read_csv(DATA_DIR / "player_stats_2025.csv")
player_stats_2026 = pd.read_csv(DATA_DIR / "player_stats_2026.csv")

## Prepare data

In [41]:
# Clean data and create features.
espn_rankings.info()
print("Missing values:\n", espn_rankings.isna().sum())
print("Duplicate rows:", espn_rankings.duplicated().sum())

datasets = {
    "2020": player_stats_2020,
    "2021": player_stats_2021,
    "2022": player_stats_2022,
    "2023": player_stats_2023,
    "2024": player_stats_2024,
    "2025": player_stats_2025,
    "2026": player_stats_2026,
}

for year, df in datasets.items():
    print(f"\n{'=' * 40}\nPlayer Stats {year}")
    df.info()
    print("Missing values:\n", df.isna().sum())
    print("Duplicate rows:", df.duplicated().sum())

    missing = df.isna().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        "Missing Count": missing,
        "Missing Percentage": missing_pct
    })

    missing_summary = missing_summary[
        missing_summary["Missing Count"] > 0
    ].sort_values("Missing Percentage", ascending=False)

    print(f"\nMissing data for {year}:")
    display(missing_summary)

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   season               600 non-null    str
 1   year                 600 non-null    int64
 2   espn_preseason_rank  600 non-null    int64
 3   player               600 non-null    str
 4   player_key           600 non-null    str
 5   espn_player_id       597 non-null    float64
 6   height_in            600 non-null    int64
 7   position             599 non-null    str
 8   class_prev_season    599 non-null    str
 9   prev_school          600 non-null    str
 10  new_school           600 non-null    str
dtypes: float64(1), int64(3), str(7)
memory usage: 83.5 KB
Missing values:
 season                 0
year                   0
espn_preseason_rank    0
player                 0
player_key             0
espn_player_id         3
height_in              0
position               1
class_prev_season      1
prev_school            0
new_school             0
dtype: int64
Duplicate rows: 0

========================================
Player Stats 2020
<class 'pandas.DataFrame'>
RangeIndex: 8835 entries, 0 to 8834
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          8835 non-null   int64
 1   seasonLabel                     8835 non-null   int64
 2   teamId                          8835 non-null   int64
 3   team                            8835 non-null   str
 4   conference                      4817 non-null   str
 5   athleteId                       8835 non-null   int64
 6   athleteSourceId                 8835 non-null   int64
 7   name                            8835 non-null   str
 8   position                        8826 non-null   str
 9   games                           8835 non-null   int64
 10  starts                          8835 non-null   int64
 11  minutes                         8835 non-null   int64
 12  points                          8835 non-null   int64
 13  turnovers                       8835 non-null   int64
 14  fouls                           8835 non-null   int64
 15  assists                         8835 non-null   int64
 16  steals                          8835 non-null   int64
 17  blocks                          8835 non-null   int64
 18  offensiveRating                 8240 non-null   float64
 19  defensiveRating                 8346 non-null   float64
 20  netRating                       7856 non-null   float64
 21  PORPAG                          8239 non-null   float64
 22  usage                           8782 non-null   float64
 23  assistsTurnoverRatio            7176 non-null   float64
 24  offensiveReboundPct             7654 non-null   float64
 25  freeThrowRate                   8245 non-null   float64
 26  effectiveFieldGoalPct           8245 non-null   float64
 27  trueShootingPct                 8321 non-null   float64
 28  fieldGoals/made                 8835 non-null   int64
 29  fieldGoals/attempted            8835 non-null   int64
 30  fieldGoals/pct                  8835 non-null   float64
 31  twoPointFieldGoals/made         8835 non-null   int64
 32  twoPointFieldGoals/attempted    8835 non-null   int64
 33  twoPointFieldGoals/pct          8835 non-null   float64
 34  threePointFieldGoals/made       8835 non-null   int64
 35  threePointFieldGoals/attempted  8835 non-null   int64
 36  threePointFieldGoals/pct        8835 non-null   float64
 37  freeThrows/made                 8835 non-null   int64
 38  freeThrows/attempted            8835 non-null   int64
 39  freeThrows/pct                  8835 non-null   float64
 40  rebounds/offensive              8835 non-null   int64
 41  rebounds/defensive              8835 non-null   int64
 42  rebounds/total                  8835 non-null   int64
 43  winShares/offensive             7881 non-null   float64
 44  winShares/defensive             8346 non-null   float64
 45  winShares/total                 7856 non-null   float64
 46  winShares/totalPer40            7856 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.4 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4018
athleteId                            0
athleteSourceId                      0
name                                 0
position                             9
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    595
defensiveRating                    489
netRating                          979
PORPAG                             596
usage                               53
assistsTurnoverRatio              1659
offensiveReboundPct               1181
freeThrowRate                      590
effectiveFieldGoalPct              590
trueShootingPct                    514
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                954
winShares/defensive                489
winShares/total                    979
winShares/totalPer40               979
dtype: int64
Duplicate rows: 0

Missing data for 2020:

                       Missing Count  Missing Percentage
conference                      4018               45.48
assistsTurnoverRatio            1659               18.78
offensiveReboundPct             1181               13.37
netRating                        979               11.08
winShares/total                  979               11.08
winShares/totalPer40             979               11.08
winShares/offensive              954               10.80
PORPAG                           596                6.75
offensiveRating                  595                6.73
freeThrowRate                    590                6.68
effectiveFieldGoalPct            590                6.68
trueShootingPct                  514                5.82
defensiveRating                  489                5.53
winShares/defensive              489                5.53
usage                             53                0.60
position                           9                0.10

========================================
Player Stats 2021
<class 'pandas.DataFrame'>
RangeIndex: 6859 entries, 0 to 6858
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          6859 non-null   int64
 1   seasonLabel                     6859 non-null   int64
 2   teamId                          6859 non-null   int64
 3   team                            6859 non-null   str
 4   conference                      5024 non-null   str
 5   athleteId                       6859 non-null   int64
 6   athleteSourceId                 6859 non-null   int64
 7   name                            6859 non-null   str
 8   position                        6852 non-null   str
 9   games                           6859 non-null   int64
 10  starts                          6859 non-null   int64
 11  minutes                         6859 non-null   int64
 12  points                          6859 non-null   int64
 13  turnovers                       6859 non-null   int64
 14  fouls                           6859 non-null   int64
 15  assists                         6859 non-null   int64
 16  steals                          6859 non-null   int64
 17  blocks                          6859 non-null   int64
 18  offensiveRating                 6466 non-null   float64
 19  defensiveRating                 6673 non-null   float64
 20  netRating                       6328 non-null   float64
 21  PORPAG                          6464 non-null   float64
 22  usage                           6840 non-null   float64
 23  assistsTurnoverRatio            5848 non-null   float64
 24  offensiveReboundPct             6222 non-null   float64
 25  freeThrowRate                   6468 non-null   float64
 26  effectiveFieldGoalPct           6468 non-null   float64
 27  trueShootingPct                 6516 non-null   float64
 28  fieldGoals/made                 6859 non-null   int64
 29  fieldGoals/attempted            6859 non-null   int64
 30  fieldGoals/pct                  6859 non-null   float64
 31  twoPointFieldGoals/made         6859 non-null   int64
 32  twoPointFieldGoals/attempted    6859 non-null   int64
 33  twoPointFieldGoals/pct          6859 non-null   float64
 34  threePointFieldGoals/made       6859 non-null   int64
 35  threePointFieldGoals/attempted  6859 non-null   int64
 36  threePointFieldGoals/pct        6859 non-null   float64
 37  freeThrows/made                 6859 non-null   int64
 38  freeThrows/attempted            6859 non-null   int64
 39  freeThrows/pct                  6859 non-null   float64
 40  rebounds/offensive              6859 non-null   int64
 41  rebounds/defensive              6859 non-null   int64
 42  rebounds/total                  6859 non-null   int64
 43  winShares/offensive             6328 non-null   float64
 44  winShares/defensive             6673 non-null   float64
 45  winShares/total                 6328 non-null   float64
 46  winShares/totalPer40            6328 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 2.7 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        1835
athleteId                            0
athleteSourceId                      0
name                                 0
position                             7
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    393
defensiveRating                    186
netRating                          531
PORPAG                             395
usage                               19
assistsTurnoverRatio              1011
offensiveReboundPct                637
freeThrowRate                      391
effectiveFieldGoalPct              391
trueShootingPct                    343
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                531
winShares/defensive                186
winShares/total                    531
winShares/totalPer40               531
dtype: int64
Duplicate rows: 0

Missing data for 2021:

                       Missing Count  Missing Percentage
conference                      1835               26.75
assistsTurnoverRatio            1011               14.74
offensiveReboundPct              637                9.29
netRating                        531                7.74
winShares/offensive              531                7.74
winShares/total                  531                7.74
winShares/totalPer40             531                7.74
PORPAG                           395                5.76
offensiveRating                  393                5.73
freeThrowRate                    391                5.70
effectiveFieldGoalPct            391                5.70
trueShootingPct                  343                5.00
defensiveRating                  186                2.71
winShares/defensive              186                2.71
usage                             19                0.28
position                           7                0.10

========================================
Player Stats 2022
<class 'pandas.DataFrame'>
RangeIndex: 9400 entries, 0 to 9399
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9400 non-null   int64
 1   seasonLabel                     9400 non-null   int64
 2   teamId                          9400 non-null   int64
 3   team                            9400 non-null   str
 4   conference                      5096 non-null   str
 5   athleteId                       9400 non-null   int64
 6   athleteSourceId                 9400 non-null   int64
 7   name                            9400 non-null   str
 8   position                        9395 non-null   str
 9   games                           9400 non-null   int64
 10  starts                          9400 non-null   int64
 11  minutes                         9400 non-null   int64
 12  points                          9400 non-null   int64
 13  turnovers                       9400 non-null   int64
 14  fouls                           9400 non-null   int64
 15  assists                         9400 non-null   int64
 16  steals                          9400 non-null   int64
 17  blocks                          9400 non-null   int64
 18  offensiveRating                 8733 non-null   float64
 19  defensiveRating                 9248 non-null   float64
 20  netRating                       8626 non-null   float64
 21  PORPAG                          8731 non-null   float64
 22  usage                           9378 non-null   float64
 23  assistsTurnoverRatio            7599 non-null   float64
 24  offensiveReboundPct             8138 non-null   float64
 25  freeThrowRate                   8778 non-null   float64
 26  effectiveFieldGoalPct           8778 non-null   float64
 27  trueShootingPct                 8852 non-null   float64
 28  fieldGoals/made                 9400 non-null   int64
 29  fieldGoals/attempted            9400 non-null   int64
 30  fieldGoals/pct                  9400 non-null   float64
 31  twoPointFieldGoals/made         9400 non-null   int64
 32  twoPointFieldGoals/attempted    9400 non-null   int64
 33  twoPointFieldGoals/pct          9400 non-null   float64
 34  threePointFieldGoals/made       9400 non-null   int64
 35  threePointFieldGoals/attempted  9400 non-null   int64
 36  threePointFieldGoals/pct        9400 non-null   float64
 37  freeThrows/made                 9400 non-null   int64
 38  freeThrows/attempted            9400 non-null   int64
 39  freeThrows/pct                  9400 non-null   float64
 40  rebounds/offensive              9400 non-null   int64
 41  rebounds/defensive              9400 non-null   int64
 42  rebounds/total                  9400 non-null   int64
 43  winShares/offensive             8628 non-null   float64
 44  winShares/defensive             9248 non-null   float64
 45  winShares/total                 8626 non-null   float64
 46  winShares/totalPer40            8626 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.6 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4304
athleteId                            0
athleteSourceId                      0
name                                 0
position                             5
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    667
defensiveRating                    152
netRating                          774
PORPAG                             669
usage                               22
assistsTurnoverRatio              1801
offensiveReboundPct               1262
freeThrowRate                      622
effectiveFieldGoalPct              622
trueShootingPct                    548
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                772
winShares/defensive                152
winShares/total                    774
winShares/totalPer40               774
dtype: int64
Duplicate rows: 0

Missing data for 2022:

                       Missing Count  Missing Percentage
conference                      4304               45.79
assistsTurnoverRatio            1801               19.16
offensiveReboundPct             1262               13.43
netRating                        774                8.23
winShares/total                  774                8.23
winShares/totalPer40             774                8.23
winShares/offensive              772                8.21
PORPAG                           669                7.12
offensiveRating                  667                7.10
freeThrowRate                    622                6.62
effectiveFieldGoalPct            622                6.62
trueShootingPct                  548                5.83
defensiveRating                  152                1.62
winShares/defensive              152                1.62
usage                             22                0.23
position                           5                0.05

========================================
Player Stats 2023
<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9752 non-null   int64
 1   seasonLabel                     9752 non-null   int64
 2   teamId                          9752 non-null   int64
 3   team                            9752 non-null   str
 4   conference                      5102 non-null   str
 5   athleteId                       9752 non-null   int64
 6   athleteSourceId                 9752 non-null   int64
 7   name                            9752 non-null   str
 8   position                        9750 non-null   str
 9   games                           9752 non-null   int64
 10  starts                          9752 non-null   int64
 11  minutes                         9752 non-null   int64
 12  points                          9752 non-null   int64
 13  turnovers                       9752 non-null   int64
 14  fouls                           9752 non-null   int64
 15  assists                         9752 non-null   int64
 16  steals                          9752 non-null   int64
 17  blocks                          9752 non-null   int64
 18  offensiveRating                 9024 non-null   float64
 19  defensiveRating                 9591 non-null   float64
 20  netRating                       8925 non-null   float64
 21  PORPAG                          9024 non-null   float64
 22  usage                           9717 non-null   float64
 23  assistsTurnoverRatio            7848 non-null   float64
 24  offensiveReboundPct             8431 non-null   float64
 25  freeThrowRate                   9058 non-null   float64
 26  effectiveFieldGoalPct           9058 non-null   float64
 27  trueShootingPct                 9138 non-null   float64
 28  fieldGoals/made                 9752 non-null   int64
 29  fieldGoals/attempted            9752 non-null   int64
 30  fieldGoals/pct                  9752 non-null   float64
 31  twoPointFieldGoals/made         9752 non-null   int64
 32  twoPointFieldGoals/attempted    9752 non-null   int64
 33  twoPointFieldGoals/pct          9752 non-null   float64
 34  threePointFieldGoals/made       9752 non-null   int64
 35  threePointFieldGoals/attempted  9752 non-null   int64
 36  threePointFieldGoals/pct        9752 non-null   float64
 37  freeThrows/made                 9752 non-null   int64
 38  freeThrows/attempted            9752 non-null   int64
 39  freeThrows/pct                  9752 non-null   float64
 40  rebounds/offensive              9752 non-null   int64
 41  rebounds/defensive              9752 non-null   int64
 42  rebounds/total                  9752 non-null   int64
 43  winShares/offensive             8925 non-null   float64
 44  winShares/defensive             9591 non-null   float64
 45  winShares/total                 8925 non-null   float64
 46  winShares/totalPer40            8925 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.8 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4650
athleteId                            0
athleteSourceId                      0
name                                 0
position                             2
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    728
defensiveRating                    161
netRating                          827
PORPAG                             728
usage                               35
assistsTurnoverRatio              1904
offensiveReboundPct               1321
freeThrowRate                      694
effectiveFieldGoalPct              694
trueShootingPct                    614
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                827
winShares/defensive                161
winShares/total                    827
winShares/totalPer40               827
dtype: int64
Duplicate rows: 0

Missing data for 2023:

                       Missing Count  Missing Percentage
conference                      4650               47.68
assistsTurnoverRatio            1904               19.52
offensiveReboundPct             1321               13.55
netRating                        827                8.48
winShares/offensive              827                8.48
winShares/total                  827                8.48
winShares/totalPer40             827                8.48
offensiveRating                  728                7.47
PORPAG                           728                7.47
freeThrowRate                    694                7.12
effectiveFieldGoalPct            694                7.12
trueShootingPct                  614                6.30
defensiveRating                  161                1.65
winShares/defensive              161                1.65
usage                             35                0.36
position                           2                0.02

========================================
Player Stats 2024
<class 'pandas.DataFrame'>
RangeIndex: 9861 entries, 0 to 9860
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9861 non-null   int64
 1   seasonLabel                     9861 non-null   int64
 2   teamId                          9861 non-null   int64
 3   team                            9861 non-null   str
 4   conference                      5063 non-null   str
 5   athleteId                       9861 non-null   int64
 6   athleteSourceId                 9861 non-null   int64
 7   name                            9861 non-null   str
 8   position                        9861 non-null   str
 9   games                           9861 non-null   int64
 10  starts                          9861 non-null   int64
 11  minutes                         9861 non-null   int64
 12  points                          9861 non-null   int64
 13  turnovers                       9861 non-null   int64
 14  fouls                           9861 non-null   int64
 15  assists                         9861 non-null   int64
 16  steals                          9861 non-null   int64
 17  blocks                          9861 non-null   int64
 18  offensiveRating                 9189 non-null   float64
 19  defensiveRating                 9786 non-null   float64
 20  netRating                       9145 non-null   float64
 21  PORPAG                          9189 non-null   float64
 22  usage                           9839 non-null   float64
 23  assistsTurnoverRatio            7786 non-null   float64
 24  offensiveReboundPct             8566 non-null   float64
 25  freeThrowRate                   9222 non-null   float64
 26  effectiveFieldGoalPct           9222 non-null   float64
 27  trueShootingPct                 9299 non-null   float64
 28  fieldGoals/made                 9861 non-null   int64
 29  fieldGoals/attempted            9861 non-null   int64
 30  fieldGoals/pct                  9861 non-null   float64
 31  twoPointFieldGoals/made         9861 non-null   int64
 32  twoPointFieldGoals/attempted    9861 non-null   int64
 33  twoPointFieldGoals/pct          9861 non-null   float64
 34  threePointFieldGoals/made       9861 non-null   int64
 35  threePointFieldGoals/attempted  9861 non-null   int64
 36  threePointFieldGoals/pct        9861 non-null   float64
 37  freeThrows/made                 9861 non-null   int64
 38  freeThrows/attempted            9861 non-null   int64
 39  freeThrows/pct                  9861 non-null   float64
 40  rebounds/offensive              9861 non-null   int64
 41  rebounds/defensive              9861 non-null   int64
 42  rebounds/total                  9861 non-null   int64
 43  winShares/offensive             9146 non-null   float64
 44  winShares/defensive             9786 non-null   float64
 45  winShares/total                 9145 non-null   float64
 46  winShares/totalPer40            9145 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.8 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4798
athleteId                            0
athleteSourceId                      0
name                                 0
position                             0
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    672
defensiveRating                     75
netRating                          716
PORPAG                             672
usage                               22
assistsTurnoverRatio              2075
offensiveReboundPct               1295
freeThrowRate                      639
effectiveFieldGoalPct              639
trueShootingPct                    562
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                715
winShares/defensive                 75
winShares/total                    716
winShares/totalPer40               716
dtype: int64
Duplicate rows: 0

Missing data for 2024:

                       Missing Count  Missing Percentage
conference                      4798               48.66
assistsTurnoverRatio            2075               21.04
offensiveReboundPct             1295               13.13
netRating                        716                7.26
winShares/total                  716                7.26
winShares/totalPer40             716                7.26
winShares/offensive              715                7.25
offensiveRating                  672                6.81
PORPAG                           672                6.81
freeThrowRate                    639                6.48
effectiveFieldGoalPct            639                6.48
trueShootingPct                  562                5.70
defensiveRating                   75                0.76
winShares/defensive               75                0.76
usage                             22                0.22

========================================
Player Stats 2025
<class 'pandas.DataFrame'>
RangeIndex: 9808 entries, 0 to 9807
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9808 non-null   int64
 1   seasonLabel                     9808 non-null   int64
 2   teamId                          9808 non-null   int64
 3   team                            9808 non-null   str
 4   conference                      5144 non-null   str
 5   athleteId                       9808 non-null   int64
 6   athleteSourceId                 9808 non-null   int64
 7   name                            9808 non-null   str
 8   position                        9786 non-null   str
 9   games                           9808 non-null   int64
 10  starts                          9808 non-null   int64
 11  minutes                         9808 non-null   int64
 12  points                          9808 non-null   int64
 13  turnovers                       9808 non-null   int64
 14  fouls                           9808 non-null   int64
 15  assists                         9808 non-null   int64
 16  steals                          9808 non-null   int64
 17  blocks                          9808 non-null   int64
 18  offensiveRating                 9130 non-null   float64
 19  defensiveRating                 9495 non-null   float64
 20  netRating                       8889 non-null   float64
 21  PORPAG                          9130 non-null   float64
 22  usage                           9771 non-null   float64
 23  assistsTurnoverRatio            7785 non-null   float64
 24  offensiveReboundPct             8470 non-null   float64
 25  freeThrowRate                   9156 non-null   float64
 26  effectiveFieldGoalPct           9156 non-null   float64
 27  trueShootingPct                 9260 non-null   float64
 28  fieldGoals/made                 9808 non-null   int64
 29  fieldGoals/attempted            9808 non-null   int64
 30  fieldGoals/pct                  9808 non-null   float64
 31  twoPointFieldGoals/made         9808 non-null   int64
 32  twoPointFieldGoals/attempted    9808 non-null   int64
 33  twoPointFieldGoals/pct          9808 non-null   float64
 34  threePointFieldGoals/made       9808 non-null   int64
 35  threePointFieldGoals/attempted  9808 non-null   int64
 36  threePointFieldGoals/pct        9808 non-null   float64
 37  freeThrows/made                 9808 non-null   int64
 38  freeThrows/attempted            9808 non-null   int64
 39  freeThrows/pct                  9808 non-null   float64
 40  rebounds/offensive              9808 non-null   int64
 41  rebounds/defensive              9808 non-null   int64
 42  rebounds/total                  9808 non-null   int64
 43  winShares/offensive             8889 non-null   float64
 44  winShares/defensive             9495 non-null   float64
 45  winShares/total                 8889 non-null   float64
 46  winShares/totalPer40            8889 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.8 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4664
athleteId                            0
athleteSourceId                      0
name                                 0
position                            22
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    678
defensiveRating                    313
netRating                          919
PORPAG                             678
usage                               37
assistsTurnoverRatio              2023
offensiveReboundPct               1338
freeThrowRate                      652
effectiveFieldGoalPct              652
trueShootingPct                    548
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                919
winShares/defensive                313
winShares/total                    919
winShares/totalPer40               919
dtype: int64
Duplicate rows: 0

Missing data for 2025:

                       Missing Count  Missing Percentage
conference                      4664               47.55
assistsTurnoverRatio            2023               20.63
offensiveReboundPct             1338               13.64
netRating                        919                9.37
winShares/offensive              919                9.37
winShares/total                  919                9.37
winShares/totalPer40             919                9.37
offensiveRating                  678                6.91
PORPAG                           678                6.91
freeThrowRate                    652                6.65
effectiveFieldGoalPct            652                6.65
trueShootingPct                  548                5.59
defensiveRating                  313                3.19
winShares/defensive              313                3.19
usage                             37                0.38
position                          22                0.22

========================================
Player Stats 2026
<class 'pandas.DataFrame'>
RangeIndex: 10030 entries, 0 to 10029
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          10030 non-null  int64
 1   seasonLabel                     10030 non-null  int64
 2   teamId                          10030 non-null  int64
 3   team                            10030 non-null  str
 4   conference                      5035 non-null   str
 5   athleteId                       10030 non-null  int64
 6   athleteSourceId                 10030 non-null  int64
 7   name                            10030 non-null  str
 8   position                        10029 non-null  str
 9   games                           10030 non-null  int64
 10  starts                          10030 non-null  int64
 11  minutes                         10030 non-null  int64
 12  points                          10030 non-null  int64
 13  turnovers                       10030 non-null  int64
 14  fouls                           10030 non-null  int64
 15  assists                         10030 non-null  int64
 16  steals                          10030 non-null  int64
 17  blocks                          10030 non-null  int64
 18  offensiveRating                 9383 non-null   float64
 19  defensiveRating                 9922 non-null   float64
 20  netRating                       9311 non-null   float64
 21  PORPAG                          9382 non-null   float64
 22  usage                           9999 non-null   float64
 23  assistsTurnoverRatio            7962 non-null   float64
 24  offensiveReboundPct             8627 non-null   float64
 25  freeThrowRate                   9385 non-null   float64
 26  effectiveFieldGoalPct           9385 non-null   float64
 27  trueShootingPct                 9455 non-null   float64
 28  fieldGoals/made                 10030 non-null  int64
 29  fieldGoals/attempted            10030 non-null  int64
 30  fieldGoals/pct                  10030 non-null  float64
 31  twoPointFieldGoals/made         10030 non-null  int64
 32  twoPointFieldGoals/attempted    10030 non-null  int64
 33  twoPointFieldGoals/pct          10030 non-null  float64
 34  threePointFieldGoals/made       10030 non-null  int64
 35  threePointFieldGoals/attempted  10030 non-null  int64
 36  threePointFieldGoals/pct        10030 non-null  float64
 37  freeThrows/made                 10030 non-null  int64
 38  freeThrows/attempted            10030 non-null  int64
 39  freeThrows/pct                  10030 non-null  float64
 40  rebounds/offensive              10030 non-null  int64
 41  rebounds/defensive              10030 non-null  int64
 42  rebounds/total                  10030 non-null  int64
 43  winShares/offensive             9312 non-null   float64
 44  winShares/defensive             9922 non-null   float64
 45  winShares/total                 9311 non-null   float64
 46  winShares/totalPer40            9311 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.9 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4995
athleteId                            0
athleteSourceId                      0
name                                 0
position                             1
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    647
defensiveRating                    108
netRating                          719
PORPAG                             648
usage                               31
assistsTurnoverRatio              2068
offensiveReboundPct               1403
freeThrowRate                      645
effectiveFieldGoalPct              645
trueShootingPct                    575
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                718
winShares/defensive                108
winShares/total                    719
winShares/totalPer40               719
dtype: int64
Duplicate rows: 0

Missing data for 2026:

                       Missing Count  Missing Percentage
conference                      4995               49.80
assistsTurnoverRatio            2068               20.62
offensiveReboundPct             1403               13.99
netRating                        719                7.17
winShares/total                  719                7.17
winShares/totalPer40             719                7.17
winShares/offensive              718                7.16
PORPAG                           648                6.46
offensiveRating                  647                6.45
freeThrowRate                    645                6.43
effectiveFieldGoalPct            645                6.43
trueShootingPct                  575                5.73
defensiveRating                  108                1.08
winShares/defensive              108                1.08
usage                             31                0.31
position                           1                0.01

### Confirm how seasons and IDs line up across datasets ###

**Clean season**

In [42]:
import numpy as np
import matplotlib.pyplot as plt

all_stats = pd.concat(datasets.values(), ignore_index=True) # Combine all datasets to explore values
print(all_stats.groupby("season")[["season", "seasonLabel"]].first()) # Group by season

        season  seasonLabel
season
2020      2020     20192020
2021      2021     20202021
2022      2022     20212022
2023      2023     20222023
2024      2024     20232024
2025      2025     20242025
2026      2026     20252026

We will define the season as the year when that season ends. For example, the 2020 season was played over 2019 and 2020. I can now delete the `seasonLabel` column in all the datasets.

In [43]:
for year, df in datasets.items():
    datasets[year] = df.drop(columns=["seasonLabel"]) # Drop seasonLabel for each dataset

print(f"Season Missing values: {all_stats["season"].isna().sum()}") # Determing missing values
datasets['2020'].head() # Check head

Season Missing values: 0

,season,teamId,team,conference,athleteId,athleteSourceId,name,position,games,starts,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,1,Abilene Christian,Southland,16870,4433077,Airion Simmons,F,31,0,...,23,39,59.0,40,87,127,0.5,0.9,1.4,0.129
1,2020,1,Abilene Christian,Southland,21203,4397957,Damien Daniels,G,31,15,...,32,43,74.4,16,58,74,0.5,0.8,1.3,0.083
2,2020,1,Abilene Christian,Southland,21204,4278255,Tobias Cameron,G,25,0,...,10,11,90.9,11,17,28,0.3,0.2,0.5,0.143
3,2020,1,Abilene Christian,Southland,21205,4397958,Joe Pleasant,F,29,29,...,68,97,70.1,49,73,122,1.3,0.7,2.0,0.112
4,2020,1,Abilene Christian,Southland,27157,4593748,Mahki Morris,G,17,1,...,14,17,82.4,14,13,27,0.0,0.4,0.4,0.084

The `season` column is good to go.

**Clean athleteID**

In [44]:
print(all_stats[["athleteId", "athleteSourceId"]].nunique()) # How many unique values are in athleteId vs athleteSourceId

print(f"\nathleteSourceIds for each athleteId:\n{all_stats.groupby('athleteId')['athleteSourceId'].nunique().value_counts()}") # Check how many sourceIds there are for each athleteID
print(all_stats[["athleteId", "athleteSourceId"]].head())

athleteId          36464
athleteSourceId    36464
dtype: int64

athleteSourceIds for each athleteId:
athleteSourceId
1    36464
Name: count, dtype: int64
   athleteId  athleteSourceId
0      16870          4433077
1      21203          4397957
2      21204          4278255
3      21205          4397958
4      27157          4593748

`athleteId` and `athleteSourceId` have different values but map one-to-one, so they carry the same information and each have the same number of unique values. Therefore, I will drop one column and just keep `athleteId`.

In [45]:
for year, df in datasets.items():
    datasets[year] = df.drop(columns=["athleteSourceId"]) # Drop athleteSourceId for each dataset

In [46]:
print(f"athleteId missing values: {all_stats['athleteId'].isna().sum()}")
datasets['2020'].head() # Check head

athleteId missing values: 0

,season,teamId,team,conference,athleteId,name,position,games,starts,minutes,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,1,Abilene Christian,Southland,16870,Airion Simmons,F,31,0,434,...,23,39,59.0,40,87,127,0.5,0.9,1.4,0.129
1,2020,1,Abilene Christian,Southland,21203,Damien Daniels,G,31,15,630,...,32,43,74.4,16,58,74,0.5,0.8,1.3,0.083
2,2020,1,Abilene Christian,Southland,21204,Tobias Cameron,G,25,0,140,...,10,11,90.9,11,17,28,0.3,0.2,0.5,0.143
3,2020,1,Abilene Christian,Southland,21205,Joe Pleasant,F,29,29,713,...,68,97,70.1,49,73,122,1.3,0.7,2.0,0.112
4,2020,1,Abilene Christian,Southland,27157,Mahki Morris,G,17,1,191,...,14,17,82.4,14,13,27,0.0,0.4,0.4,0.084

In [47]:
rows_per_athlete = all_stats.groupby(["season", "athleteId"]).size() # Group by season and athleteId to see how many ahtletes are featured multiple times in one season
print(f"Rows per athlete within a season:\n{rows_per_athlete.value_counts()}")

print(f"\nNumber of duplicate athletes by season:\n{(rows_per_athlete > 1).groupby("season").sum()}")

Rows per athlete within a season:
1    64405
2       70
Name: count, dtype: int64

Number of duplicate athletes by season:
season
2020    38
2021     5
2022     5
2023     0
2024     0
2025    20
2026     2
dtype: int64

I looked at how many athletes are featured multiple times in just one season, and saw that there are 70 players who appear twice. This means that only 70 out of 64,475 athlete-seasons (0.1%) have a repeat. I am going to see what those 70 cases are. No players appear three times.

In [48]:
duplicates = all_stats[all_stats.duplicated(subset=["season", "athleteId"], keep=False)] # Find all the duplicated players
print(duplicates.sort_values(["athleteId", "season"])[["athleteId", "name", "season", "team", "games", "points"]].to_string(index=False)) # Inspect the duplicated players

 athleteId                 name  season                     team  games  points
      4605        Brendan Terry    2025 Southeast Missouri State     33     370
      4605        Brendan Terry    2025            UNC Asheville      1       7
      4606              TJ Biel    2025 Southeast Missouri State     31     116
      4606              TJ Biel    2025            UNC Asheville      1       0
      4607           Rob Martin    2025 Southeast Missouri State     33     488
      4607           Rob Martin    2025            UNC Asheville      1      13
      4608       Elliot Lowndes    2025 Southeast Missouri State     33      75
      4608       Elliot Lowndes    2025            UNC Asheville      1       5
      4611          David Idada    2025 Southeast Missouri State     33      68
      4611          David Idada    2025            UNC Asheville      1       0
      4612        Troy Cole Jr.    2025 Southeast Missouri State     33     192
      4612        Troy Cole Jr.    2025            UNC Asheville      1       5
      4613      Damarion Walkup    2025 Southeast Missouri State     27      89
      4613      Damarion Walkup    2025            UNC Asheville      1       1
      4614        Marqueas Bell    2025 Southeast Missouri State     19      64
      4614        Marqueas Bell    2025            UNC Asheville      1       8
      4615              BJ Ward    2025 Southeast Missouri State     33     278
      4615              BJ Ward    2025            UNC Asheville      1      10
      4616 Teddy Washington Jr.    2025 Southeast Missouri State     32     444
      4616 Teddy Washington Jr.    2025            UNC Asheville      1      15
      4854     Christian Wright    2022                  Georgia     32     169
      4854     Christian Wright    2022             Northwestern      1       9
      5098      Jaylen Peterson    2025           Illinois State      1       4
      5098      Jaylen Peterson    2025             Presbyterian     32     195
      5099          Kaleb Scott    2025           Illinois State      1       6
      5099          Kaleb Scott    2025             Presbyterian     32     292
      5100           Kory Mincy    2025           Illinois State      1      21
      5100           Kory Mincy    2025             Presbyterian     32     476
      5101       Jamahri Harvey    2025           Illinois State      1       3
      5101       Jamahri Harvey    2025             Presbyterian     31     233
      5102         Kobe Stewart    2025           Illinois State      1      15
      5102         Kobe Stewart    2025             Presbyterian     32     491
      5104         Iverson King    2025           Illinois State      1       0
      5104         Iverson King    2025             Presbyterian     32     184
      5105         Carl Parrish    2025           Illinois State      1       4
      5105         Carl Parrish    2025             Presbyterian     31     216
      5106      Quadir Pettaway    2025           Illinois State      1      10
      5106      Quadir Pettaway    2025             Presbyterian     31     103
      5108       Triston Wilson    2025           Illinois State      1       7
      5108       Triston Wilson    2025             Presbyterian     29      68
      5111        Houston Jones    2025           Illinois State      1       0
      5111        Houston Jones    2025             Presbyterian      9      11
      5155          Jaden House    2022               High Point     31     381
      5155          Jaden House    2022                 Winthrop      1      12
      6097      Dylan Brumfield    2026            Southern Miss     35     295
      6097      Dylan Brumfield    2026            William Carey      1       5
      7363         Pape N'Diaye    2026                   Xavier     29      58
      7363         Pape N'Diaye    2026          Calumet College      1       2
      7555        Rondel Walker    2021           Oklahoma State     29     226
      7555        Rondel Walker    2021               Texas Tech      1       2
     10317          Ethan Kieke    2020         UT Permian Basin      1       2
     10317          Ethan Kieke    2020      Texas Permian Basin      1       3
     10318     Donoven Carlisle    2020         UT Permian Basin      1      11
     10318     Donoven Carlisle    2020      Texas Permian Basin      1      10
     10323      Elvin Rodriguez    2020         UT Permian Basin      1       0
     10323      Elvin Rodriguez    2020      Texas Permian Basin      1       9
     10324      Fermandez Jones    2020         UT Permian Basin      1       4
     10324      Fermandez Jones    2020      Texas Permian Basin      1       4
     10325          Pat Dembley    2020         UT Permian Basin      1       9
     10325          Pat Dembley    2020      Texas Permian Basin      1      13
     10327       Malik Anderson    2020         UT Permian Basin      1       0
     10327       Malik Anderson    2020      Texas Permian Basin      1       8
     15205    Emmanuel Izunabor    2022               High Point     32     162
     15205    Emmanuel Izunabor    2022                 Winthrop      1       1
     15213       Brock Williams    2022               High Point     21      35
     15213       Brock Williams    2022                 Winthrop      1       0
     16406        DaJuan Gordon    2020                  Bradley      1       4
     16406        DaJuan Gordon    2020             Kansas State     32     201
     16493       Antonio Thomas    2020                  Bradley     33      55
     16493       Antonio Thomas    2020             Kansas State      1       0
     16876  John-Michael Wright    2022               High Point     32     588
     16876  John-Michael Wright    2022                 Winthrop      1       9
     16954   Avery Anderson III    2021           Oklahoma State     27     329
     16954   Avery Anderson III    2021               Texas Tech      1      16
     21233       Shaun Williams    2020                  Bradley      1      10
     21233       Shaun Williams    2020             Kansas State      5      18
     21237      Stephan Gabriel    2020                  Bradley     12      48
     21237      Stephan Gabriel    2020             Kansas State      1       0
     21449        Ja'Shon Henry    2020                  Bradley     33     312
     21449        Ja'Shon Henry    2020             Kansas State      1      11
     21450    Ville Tahvanainen    2020                  Bradley     33     217
     21450    Ville Tahvanainen    2020             Kansas State      1       0
     25974    Levi Stockard III    2020                  Bradley      1       2
     25974    Levi Stockard III    2020             Kansas State     32     120
     26836       Antonio Gordon    2020                  Bradley      1       4
     26836       Antonio Gordon    2020             Kansas State     26     109
     27397      Antonio Gardner    2020           Carver College      1      11
     27397      Antonio Gardner    2020           Carver College      4      26
     27398         Jessy Haynes    2020           Carver College      1      15
     27398         Jessy Haynes    2020           Carver College      5      37
     27399           Glenn Sims    2020           Carver College      1       2
     27399           Glenn Sims    2020           Carver College      4       7
     27403        Maxamus Simms    2020           Carver College      1       0
     27403        Maxamus Simms    2020           Carver College      1       1
     27404        Jhonny Lutula    2020           Carver College      1       4
     27404        Jhonny Lutula    2020           Carver College      5      45
     27405        Keith Krouser    2020           Carver College      1       0
     27405        Keith Krouser    2020           Carver College      5      11
     27406   Rayford Washington    2020           Carver College      1       5
     27406   Rayford Washington    2020           Carver College      3      24
     27407       Tyler Thornton    2020           Carver College      1       8
     27407       Tyler Thornton    2020           Carver College      4      20
     27408        Julian Fuller    2020           Carver College      1       4
     27408        Julian Fuller    2020           Carver College      3       9
     27409      Marquel Gibbons    2020           Carver College      1       5
     27409      Marquel Gibbons    2020           Carver College      5      31
     27410        Chris Iverson    2020           Carver College      1      10
     27410        Chris Iverson    2020           Carver College      5      27
     27530        Danya Kingsby    2020                  Bradley     33     239
     27530        Danya Kingsby    2020             Kansas State      1       8
     27587             Ari Boya    2020                  Bradley     31      94
     27587             Ari Boya    2020             Kansas State      1       0
     27975         Mike McGuirl    2020                  Bradley      1      10
     27975         Mike McGuirl    2020             Kansas State     29     200
     28308          David Sloan    2020                  Bradley      1       0
     28308          David Sloan    2020             Kansas State     32     171
     31449          A.J. Lawson    2020                  McNeese     32     478
     31449          A.J. Lawson    2020           South Carolina     31     416
     31449          A.J. Lawson    2021                  McNeese     23     271
     31449          A.J. Lawson    2021           South Carolina     21     349
     31475       Cartier Diarra    2020                  Bradley      1       6
     31475       Cartier Diarra    2020             Kansas State     32     424
     31487    Babatunde Sowunmi    2021                  Oakland      2       0
     31487    Babatunde Sowunmi    2021               Point Park      2       0
     31643        Elijah Childs    2020                  Bradley     22     325
     31643        Elijah Childs    2020             Kansas State      1      12
     31717      Cade Cunningham    2021           Oklahoma State     27     544
     31717      Cade Cunningham    2021               Texas Tech      1      20
     35461             Koch Bar    2020                  Bradley     34     212
     35461             Koch Bar    2020             Kansas State      1       4
     35462         Nate Kennell    2020                  Bradley     34     426
     35462         Nate Kennell    2020             Kansas State      1      22
     35463        Darrell Brown    2020                  Bradley     32     495
     35463        Darrell Brown    2020             Kansas State      1      16
     35993         Xavier Sneed    2020                  Bradley      1      15
     35993         Xavier Sneed    2020             Kansas State     32     455
     35994         Makol Mawien    2020                  Bradley      1       9
     35994         Makol Mawien    2020             Kansas State     32     238
     35995       Pierson McAtee    2020                  Bradley      1       0
     35995       Pierson McAtee    2020             Kansas State     21      19

The athletes that are duplicated within a season are shown on different teams in the same season. I did some research, using Brendan Terry as an example, and found that the Southeast Missouri State players who played in their game against UNC Asheville each have a separate row for that game, where they are mislabeled as UNC Asheville players. The points in those rows match the points the players scored in that game's box score. 

The only exception is A.J. Lawson. He is the only athlete where one of his two rows isn't a single game. After researching, I found out this is two different A.J. Lawsons with the same `athleteId` (31449). One played for South Carolina, and the other played for McNeese. I will separate these players and give one of them a different `athleteID`.

After this, for each duplicated athlete, I will keep the row with the most games, since that is the team they actually played for.

In [49]:
# athleteId 31449 is shared by two different players named A.J. Lawson (McNeese and South Carolina)
# Give the South Carolina player his own ID so the two are no longer mixed up.
new_id = max(df["athleteId"].max() for df in datasets.values()) + 1 # Determine the max athleteId and add one

for year, df in datasets.items(): # Give the SC player a new athleteId
    is_sc_lawson = (df["athleteId"] == 31449) & (df["team"] == "South Carolina")
    df.loc[is_sc_lawson, "athleteId"] = new_id

In [50]:
for year, df in datasets.items():
    # For athletes with two team rows in one season, keep the row with the most games (or minutes if games are tied)
    df = df.sort_values(["games", "minutes"], ascending=False)
    df = df.drop_duplicates(subset=["season", "athleteId"], keep="first")
    datasets[year] = df.sort_values("athleteId").reset_index(drop=True)

all_stats = pd.concat(datasets.values(), ignore_index=True) # Rebuild combined table from cleaned datasets

print(f"Duplicate athlete-seasons left: {all_stats.duplicated(subset=['season', 'athleteId']).sum()}") # Check how many duplicates are left
print(f"Rows: {len(all_stats)}\n")
print("A.J. Lawson after the split:")
print(all_stats[all_stats["name"] == "A.J. Lawson"][["athleteId", "season", "team", "games"]]
      .sort_values(["athleteId", "season"]).to_string(index=False))
datasets['2020'].head() # Check head

Duplicate athlete-seasons left: 0
Rows: 64477

A.J. Lawson after the split:
 athleteId  season           team  games
     31449    2020        McNeese     32
     31449    2021        McNeese     23
    223021    2020 South Carolina     31
    223021    2021 South Carolina     21

,season,teamId,team,conference,athleteId,name,position,games,starts,minutes,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,58,Columbia,Ivy,41,Cameron Shockley-Okeke,F,13,0,143,...,3,4,75.0,5,19,24,-0.4,0.3,-0.1,-0.028
1,2020,235,Providence,Big East,67,Greg Gantt Jr.,F,27,5,338,...,13,19,68.4,26,36,62,0.0,0.7,0.7,0.083
2,2020,299,The Citadel,SoCon,70,Fletcher Abee,G,30,30,969,...,45,53,84.9,10,47,57,1.8,0.4,2.2,0.091
3,2020,145,Long Beach State,Big West,96,Romelle Mansel,F,32,23,631,...,32,65,49.2,29,84,113,-0.7,0.5,-0.2,-0.013
4,2020,148,Louisiana,Sun Belt,122,Mylik Wilson,G,29,24,991,...,48,68,70.6,34,132,166,0.8,1.5,2.3,0.093

The duplicate athletes were handled correctly.

In [51]:
print(f"athleteIds with more than one name: {(all_stats.groupby('athleteId')['name'].nunique() > 1).sum()}") # Check names and athleteId

year_shifted_forward = all_stats.copy() # Copy the table
year_shifted_forward["season"] = year_shifted_forward["season"] + 1 # Add one to each season to check how athleteId's move between the prior season 

both_years = all_stats.merge(year_shifted_forward, on=["athleteId", "season"], suffixes=("_this_year", "_last_year")) # Inner join each player's rows with his row from the year before

changed_team = both_years["teamId_this_year"] != both_years["teamId_last_year"] # Check to see if teamId is different from year to year

print(f"Players found in two consecutive seasons: {len(both_years)}")
print(f"Players found in two consecutive seasons who changed teams: {changed_team.sum()}")

athleteIds with more than one name: 0
Players found in two consecutive seasons: 25172
Players found in two consecutive seasons who changed teams: 6194

No `athleteId`s have more than one name, and the same `athleteId` shows up across consecutive seasons, even when a player changes teams, which is great news. There are 6,194 cases of a player appearing on a different team than the season before. This does include non-D1 schools, so this number will shrink once we filter to D1. The `athleteID` column is good to go.

### Build transfers DataFrame

In [52]:
transfers = both_years[both_years["teamId_this_year"] != both_years["teamId_last_year"]]
transfers.info()
transfers[['name_this_year','team_this_year','team_last_year']]

<class 'pandas.DataFrame'>
Index: 6194 entries, 5 to 25166
Data columns (total 88 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   season                                    6194 non-null   int64
 1   teamId_this_year                          6194 non-null   int64
 2   team_this_year                            6194 non-null   str
 3   conference_this_year                      5697 non-null   str
 4   athleteId                                 6194 non-null   int64
 5   name_this_year                            6194 non-null   str
 6   position_this_year                        6194 non-null   str
 7   games_this_year                           6194 non-null   int64
 8   starts_this_year                          6194 non-null   int64
 9   minutes_this_year                         6194 non-null   int64
 10  points_this_year                          6194 non-null   int64
 11  turnovers_this_year                       6194 non-null   int64
 12  fouls_this_year                           6194 non-null   int64
 13  assists_this_year                         6194 non-null   int64
 14  steals_this_year                          6194 non-null   int64
 15  blocks_this_year                          6194 non-null   int64
 16  offensiveRating_this_year                 6128 non-null   float64
 17  defensiveRating_this_year                 6172 non-null   float64
 18  netRating_this_year                       6112 non-null   float64
 19  PORPAG_this_year                          6128 non-null   float64
 20  usage_this_year                           6189 non-null   float64
 21  assistsTurnoverRatio_this_year            5967 non-null   float64
 22  offensiveReboundPct_this_year             6072 non-null   float64
 23  freeThrowRate_this_year                   6130 non-null   float64
 24  effectiveFieldGoalPct_this_year           6130 non-null   float64
 25  trueShootingPct_this_year                 6140 non-null   float64
 26  fieldGoals/made_this_year                 6194 non-null   int64
 27  fieldGoals/attempted_this_year            6194 non-null   int64
 28  fieldGoals/pct_this_year                  6194 non-null   float64
 29  twoPointFieldGoals/made_this_year         6194 non-null   int64
 30  twoPointFieldGoals/attempted_this_year    6194 non-null   int64
 31  twoPointFieldGoals/pct_this_year          6194 non-null   float64
 32  threePointFieldGoals/made_this_year       6194 non-null   int64
 33  threePointFieldGoals/attempted_this_year  6194 non-null   int64
 34  threePointFieldGoals/pct_this_year        6194 non-null   float64
 35  freeThrows/made_this_year                 6194 non-null   int64
 36  freeThrows/attempted_this_year            6194 non-null   int64
 37  freeThrows/pct_this_year                  6194 non-null   float64
 38  rebounds/offensive_this_year              6194 non-null   int64
 39  rebounds/defensive_this_year              6194 non-null   int64
 40  rebounds/total_this_year                  6194 non-null   int64
 41  winShares/offensive_this_year             6113 non-null   float64
 42  winShares/defensive_this_year             6172 non-null   float64
 43  winShares/total_this_year                 6112 non-null   float64
 44  winShares/totalPer40_this_year            6112 non-null   float64
 45  teamId_last_year                          6194 non-null   int64
 46  team_last_year                            6194 non-null   str
 47  conference_last_year                      5761 non-null   str
 48  name_last_year                            6194 non-null   str
 49  position_last_year                        6194 non-null   str
 50  games_last_year                           6194 non-null   int64
 51  starts_last_year                          6194 non-null   int64
 52  minutes_last_year                         6194 non-null   int64
 53  points_last_year                          6194 non-null   int64
 54  turnovers_last_year                       6194 non-null   int64
 55  fouls_last_year                           6194 non-null   int64
 56  assists_last_year                         6194 non-null   int64
 57  steals_last_year                          6194 non-null   int64
 58  blocks_last_year                          6194 non-null   int64
 59  offensiveRating_last_year                 6114 non-null   float64
 60  defensiveRating_last_year                 6148 non-null   float64
 61  netRating_last_year                       6079 non-null   float64
 62  PORPAG_last_year                          6114 non-null   float64
 63  usage_last_year                           6188 non-null   float64
 64  assistsTurnoverRatio_last_year            5901 non-null   float64
 65  offensiveReboundPct_last_year             6024 non-null   float64
 66  freeThrowRate_last_year                   6117 non-null   float64
 67  effectiveFieldGoalPct_last_year           6117 non-null   float64
 68  trueShootingPct_last_year                 6132 non-null   float64
 69  fieldGoals/made_last_year                 6194 non-null   int64
 70  fieldGoals/attempted_last_year            6194 non-null   int64
 71  fieldGoals/pct_last_year                  6194 non-null   float64
 72  twoPointFieldGoals/made_last_year         6194 non-null   int64
 73  twoPointFieldGoals/attempted_last_year    6194 non-null   int64
 74  twoPointFieldGoals/pct_last_year          6194 non-null   float64
 75  threePointFieldGoals/made_last_year       6194 non-null   int64
 76  threePointFieldGoals/attempted_last_year  6194 non-null   int64
 77  threePointFieldGoals/pct_last_year        6194 non-null   float64
 78  freeThrows/made_last_year                 6194 non-null   int64
 79  freeThrows/attempted_last_year            6194 non-null   int64
 80  freeThrows/pct_last_year                  6194 non-null   float64
 81  rebounds/offensive_last_year              6194 non-null   int64
 82  rebounds/defensive_last_year              6194 non-null   int64
 83  rebounds/total_last_year                  6194 non-null   int64
 84  winShares/offensive_last_year             6079 non-null   float64
 85  winShares/defensive_last_year             6148 non-null   float64
 86  winShares/total_last_year                 6079 non-null   float64
 87  winShares/totalPer40_last_year            6079 non-null   float64
dtypes: float64(36), int64(44), str(8)
memory usage: 4.6 MB

          name_this_year        team_this_year       team_last_year
5          Khalif Battle                Temple               Butler
7         Matt Van Komen          Saint Mary's                 Utah
30           C.J. Walker                   UCF               Oregon
47        Jordan Brinson           Utah Valley                  UAB
52         Jalen Windham            Ball State            Creighton
...                  ...                   ...                  ...
25158    Daniel McCollum        Lehman College         Medgar Evers
25159     Doctor Bradley       Bethune-Cookman  Arkansas-Pine Bluff
25161       Elijah Davis          Morgan State          Bowie State
25163       Kevon Corley  District Of Columbia          Bowie State
25166  Cedric Taylor III                Howard            Morehouse

[6194 rows x 3 columns]

In [53]:
with pd.option_context('display.max_rows', None):
    # Filter the series to only show columns where the missing count is not 0
    missing_counts = transfers.isna().sum().sort_values(ascending=False)
    print("Missing values:\n", missing_counts[missing_counts != 0])

Missing values:
 conference_this_year               497
conference_last_year               433
assistsTurnoverRatio_last_year     293
assistsTurnoverRatio_this_year     227
offensiveReboundPct_last_year      170
offensiveReboundPct_this_year      122
winShares/totalPer40_last_year     115
winShares/total_last_year          115
winShares/offensive_last_year      115
netRating_last_year                115
netRating_this_year                 82
winShares/total_this_year           82
winShares/totalPer40_this_year      82
winShares/offensive_this_year       81
offensiveRating_last_year           80
PORPAG_last_year                    80
effectiveFieldGoalPct_last_year     77
freeThrowRate_last_year             77
PORPAG_this_year                    66
offensiveRating_this_year           66
freeThrowRate_this_year             64
effectiveFieldGoalPct_this_year     64
trueShootingPct_last_year           62
trueShootingPct_this_year           54
winShares/defensive_last_year       46
defensiveRating_last_year           46
defensiveRating_this_year           22
winShares/defensive_this_year       22
usage_last_year                      6
usage_this_year                      5
dtype: int64

After combining current and prior year statistics and filtering down to just players who changed schools (i.e. transferred), there are 6,194 transfers across years in the dataset. Each row has the statistics from the current season and the prior season, which are labeled with a `_this_year` or `_last_year` suffix. This is a large enough dataset to build our models on.

In [ ]:
transfers.to_csv("data/transfers.csv", index=False) # Save down the new transfers dataset

## Explore data

In [55]:
# Summarize and visualize the prepared data.

## Build models

In [56]:
# Train baseline and candidate models.

## Evaluate models

In [57]:
# Compare models using the chosen evaluation measures.

## Final results

In [58]:
# Generate the final tables and figures.

## AI usage disclosure

- **AI tool/model:** [Name the tool and model, or state that no generative AI was used.]
- **Used for:** [Briefly identify the tasks.]
- **How we verified the work:** [Briefly identify the checks.]
- **Prompt(s) used:** [Paste the prompts used.]