# [Project title]

**Team members:** [Names]  
**Repository:** https://github.com/eviemcmahan/ds_3001_project_team_6.git

## Setup

Use relative paths and keep the notebook runnable from beginning to end.

In [1]:
from pathlib import Path

DATA_DIR = Path("data")
assert DATA_DIR.is_dir(), "The data directory is missing."

## Load data

In [2]:
# Load data from DATA_DIR.
!pip install pandas
import pandas as pd

espn_rankings = pd.read_csv(DATA_DIR / "espn_preseason_rankings.csv")
player_stats_2020 = pd.read_csv(DATA_DIR / "player_stats_2020.csv")
player_stats_2021 = pd.read_csv(DATA_DIR / "player_stats_2021.csv")
player_stats_2022 = pd.read_csv(DATA_DIR / "player_stats_2022.csv")
player_stats_2023 = pd.read_csv(DATA_DIR / "player_stats_2023.csv")
player_stats_2024 = pd.read_csv(DATA_DIR / "player_stats_2024.csv")
player_stats_2025 = pd.read_csv(DATA_DIR / "player_stats_2025.csv")
player_stats_2026 = pd.read_csv(DATA_DIR / "player_stats_2026.csv")

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Prepare data

In [3]:
# Clean data and create features.
espn_rankings.info()
print("Missing values:\n", espn_rankings.isna().sum())
print("Duplicate rows:", espn_rankings.duplicated().sum())

datasets = {
    "2020": player_stats_2020,
    "2021": player_stats_2021,
    "2022": player_stats_2022,
    "2023": player_stats_2023,
    "2024": player_stats_2024,
    "2025": player_stats_2025,
    "2026": player_stats_2026,
}

for year, df in datasets.items():
    print(f"\n{'=' * 40}\nPlayer Stats {year}")
    df.info()
    print("Missing values:\n", df.isna().sum())
    print("Duplicate rows:", df.duplicated().sum())

    missing = df.isna().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        "Missing Count": missing,
        "Missing Percentage": missing_pct
    })

    missing_summary = missing_summary[
        missing_summary["Missing Count"] > 0
    ].sort_values("Missing Percentage", ascending=False)

    print(f"\nMissing data for {year}:")
    display(missing_summary)

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   season               600 non-null    str
 1   year                 600 non-null    int64
 2   espn_preseason_rank  600 non-null    int64
 3   player               600 non-null    str
 4   player_key           600 non-null    str
 5   espn_player_id       597 non-null    float64
 6   height_in            600 non-null    int64
 7   position             599 non-null    str
 8   class_prev_season    599 non-null    str
 9   prev_school          600 non-null    str
 10  new_school           600 non-null    str
dtypes: float64(1), int64(3), str(7)
memory usage: 51.7 KB
Missing values:
 season                 0
year                   0
espn_preseason_rank    0
player                 0
player_key             0
espn_player_id         3
height_in              0
position               1
class_prev_season      1
prev_school            0
new_school             0
dtype: int64
Duplicate rows: 0

========================================
Player Stats 2020
<class 'pandas.DataFrame'>
RangeIndex: 8835 entries, 0 to 8834
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          8835 non-null   int64
 1   seasonLabel                     8835 non-null   int64
 2   teamId                          8835 non-null   int64
 3   team                            8835 non-null   str
 4   conference                      6902 non-null   str
 5   athleteId                       8835 non-null   int64
 6   athleteSourceId                 8835 non-null   int64
 7   name                            8835 non-null   str
 8   position                        8826 non-null   str
 9   games                           8835 non-null   int64
 10  starts                          8835 non-null   int64
 11  minutes                         8835 non-null   int64
 12  points                          8835 non-null   int64
 13  turnovers                       8835 non-null   int64
 14  fouls                           8835 non-null   int64
 15  assists                         8835 non-null   int64
 16  steals                          8835 non-null   int64
 17  blocks                          8835 non-null   int64
 18  offensiveRating                 8240 non-null   float64
 19  defensiveRating                 8346 non-null   float64
 20  netRating                       7856 non-null   float64
 21  PORPAG                          8239 non-null   float64
 22  usage                           8782 non-null   float64
 23  assistsTurnoverRatio            7176 non-null   float64
 24  offensiveReboundPct             7654 non-null   float64
 25  freeThrowRate                   8245 non-null   float64
 26  effectiveFieldGoalPct           8245 non-null   float64
 27  trueShootingPct                 8321 non-null   float64
 28  fieldGoals/made                 8835 non-null   int64
 29  fieldGoals/attempted            8835 non-null   int64
 30  fieldGoals/pct                  8835 non-null   float64
 31  twoPointFieldGoals/made         8835 non-null   int64
 32  twoPointFieldGoals/attempted    8835 non-null   int64
 33  twoPointFieldGoals/pct          8835 non-null   float64
 34  threePointFieldGoals/made       8835 non-null   int64
 35  threePointFieldGoals/attempted  8835 non-null   int64
 36  threePointFieldGoals/pct        8835 non-null   float64
 37  freeThrows/made                 8835 non-null   int64
 38  freeThrows/attempted            8835 non-null   int64
 39  freeThrows/pct                  8835 non-null   float64
 40  rebounds/offensive              8835 non-null   int64
 41  rebounds/defensive              8835 non-null   int64
 42  rebounds/total                  8835 non-null   int64
 43  winShares/offensive             7881 non-null   float64
 44  winShares/defensive             8346 non-null   float64
 45  winShares/total                 7856 non-null   float64
 46  winShares/totalPer40            7856 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.2 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        1933
athleteId                            0
athleteSourceId                      0
name                                 0
position                             9
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    595
defensiveRating                    489
netRating                          979
PORPAG                             596
usage                               53
assistsTurnoverRatio              1659
offensiveReboundPct               1181
freeThrowRate                      590
effectiveFieldGoalPct              590
trueShootingPct                    514
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                954
winShares/defensive                489
winShares/total                    979
winShares/totalPer40               979
dtype: int64
Duplicate rows: 0

Missing data for 2020:

                       Missing Count  Missing Percentage
conference                      1933               21.88
assistsTurnoverRatio            1659               18.78
offensiveReboundPct             1181               13.37
netRating                        979               11.08
winShares/totalPer40             979               11.08
winShares/total                  979               11.08
winShares/offensive              954               10.80
PORPAG                           596                6.75
offensiveRating                  595                6.73
freeThrowRate                    590                6.68
effectiveFieldGoalPct            590                6.68
trueShootingPct                  514                5.82
defensiveRating                  489                5.53
winShares/defensive              489                5.53
usage                             53                0.60
position                           9                0.10

========================================
Player Stats 2021
<class 'pandas.DataFrame'>
RangeIndex: 6859 entries, 0 to 6858
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          6859 non-null   int64
 1   seasonLabel                     6859 non-null   int64
 2   teamId                          6859 non-null   int64
 3   team                            6859 non-null   str
 4   conference                      5024 non-null   str
 5   athleteId                       6859 non-null   int64
 6   athleteSourceId                 6859 non-null   int64
 7   name                            6859 non-null   str
 8   position                        6852 non-null   str
 9   games                           6859 non-null   int64
 10  starts                          6859 non-null   int64
 11  minutes                         6859 non-null   int64
 12  points                          6859 non-null   int64
 13  turnovers                       6859 non-null   int64
 14  fouls                           6859 non-null   int64
 15  assists                         6859 non-null   int64
 16  steals                          6859 non-null   int64
 17  blocks                          6859 non-null   int64
 18  offensiveRating                 6466 non-null   float64
 19  defensiveRating                 6673 non-null   float64
 20  netRating                       6328 non-null   float64
 21  PORPAG                          6464 non-null   float64
 22  usage                           6840 non-null   float64
 23  assistsTurnoverRatio            5848 non-null   float64
 24  offensiveReboundPct             6222 non-null   float64
 25  freeThrowRate                   6468 non-null   float64
 26  effectiveFieldGoalPct           6468 non-null   float64
 27  trueShootingPct                 6516 non-null   float64
 28  fieldGoals/made                 6859 non-null   int64
 29  fieldGoals/attempted            6859 non-null   int64
 30  fieldGoals/pct                  6859 non-null   float64
 31  twoPointFieldGoals/made         6859 non-null   int64
 32  twoPointFieldGoals/attempted    6859 non-null   int64
 33  twoPointFieldGoals/pct          6859 non-null   float64
 34  threePointFieldGoals/made       6859 non-null   int64
 35  threePointFieldGoals/attempted  6859 non-null   int64
 36  threePointFieldGoals/pct        6859 non-null   float64
 37  freeThrows/made                 6859 non-null   int64
 38  freeThrows/attempted            6859 non-null   int64
 39  freeThrows/pct                  6859 non-null   float64
 40  rebounds/offensive              6859 non-null   int64
 41  rebounds/defensive              6859 non-null   int64
 42  rebounds/total                  6859 non-null   int64
 43  winShares/offensive             6328 non-null   float64
 44  winShares/defensive             6673 non-null   float64
 45  winShares/total                 6328 non-null   float64
 46  winShares/totalPer40            6328 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 2.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        1835
athleteId                            0
athleteSourceId                      0
name                                 0
position                             7
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    393
defensiveRating                    186
netRating                          531
PORPAG                             395
usage                               19
assistsTurnoverRatio              1011
offensiveReboundPct                637
freeThrowRate                      391
effectiveFieldGoalPct              391
trueShootingPct                    343
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                531
winShares/defensive                186
winShares/total                    531
winShares/totalPer40               531
dtype: int64
Duplicate rows: 0

Missing data for 2021:

                       Missing Count  Missing Percentage
conference                      1835               26.75
assistsTurnoverRatio            1011               14.74
offensiveReboundPct              637                9.29
netRating                        531                7.74
winShares/offensive              531                7.74
winShares/total                  531                7.74
winShares/totalPer40             531                7.74
PORPAG                           395                5.76
offensiveRating                  393                5.73
freeThrowRate                    391                5.70
effectiveFieldGoalPct            391                5.70
trueShootingPct                  343                5.00
defensiveRating                  186                2.71
winShares/defensive              186                2.71
usage                             19                0.28
position                           7                0.10

========================================
Player Stats 2022
<class 'pandas.DataFrame'>
RangeIndex: 9400 entries, 0 to 9399
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9400 non-null   int64
 1   seasonLabel                     9400 non-null   int64
 2   teamId                          9400 non-null   int64
 3   team                            9400 non-null   str
 4   conference                      5096 non-null   str
 5   athleteId                       9400 non-null   int64
 6   athleteSourceId                 9400 non-null   int64
 7   name                            9400 non-null   str
 8   position                        9395 non-null   str
 9   games                           9400 non-null   int64
 10  starts                          9400 non-null   int64
 11  minutes                         9400 non-null   int64
 12  points                          9400 non-null   int64
 13  turnovers                       9400 non-null   int64
 14  fouls                           9400 non-null   int64
 15  assists                         9400 non-null   int64
 16  steals                          9400 non-null   int64
 17  blocks                          9400 non-null   int64
 18  offensiveRating                 8733 non-null   float64
 19  defensiveRating                 9248 non-null   float64
 20  netRating                       8626 non-null   float64
 21  PORPAG                          8731 non-null   float64
 22  usage                           9378 non-null   float64
 23  assistsTurnoverRatio            7599 non-null   float64
 24  offensiveReboundPct             8138 non-null   float64
 25  freeThrowRate                   8778 non-null   float64
 26  effectiveFieldGoalPct           8778 non-null   float64
 27  trueShootingPct                 8852 non-null   float64
 28  fieldGoals/made                 9400 non-null   int64
 29  fieldGoals/attempted            9400 non-null   int64
 30  fieldGoals/pct                  9400 non-null   float64
 31  twoPointFieldGoals/made         9400 non-null   int64
 32  twoPointFieldGoals/attempted    9400 non-null   int64
 33  twoPointFieldGoals/pct          9400 non-null   float64
 34  threePointFieldGoals/made       9400 non-null   int64
 35  threePointFieldGoals/attempted  9400 non-null   int64
 36  threePointFieldGoals/pct        9400 non-null   float64
 37  freeThrows/made                 9400 non-null   int64
 38  freeThrows/attempted            9400 non-null   int64
 39  freeThrows/pct                  9400 non-null   float64
 40  rebounds/offensive              9400 non-null   int64
 41  rebounds/defensive              9400 non-null   int64
 42  rebounds/total                  9400 non-null   int64
 43  winShares/offensive             8628 non-null   float64
 44  winShares/defensive             9248 non-null   float64
 45  winShares/total                 8626 non-null   float64
 46  winShares/totalPer40            8626 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.4 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4304
athleteId                            0
athleteSourceId                      0
name                                 0
position                             5
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    667
defensiveRating                    152
netRating                          774
PORPAG                             669
usage                               22
assistsTurnoverRatio              1801
offensiveReboundPct               1262
freeThrowRate                      622
effectiveFieldGoalPct              622
trueShootingPct                    548
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                772
winShares/defensive                152
winShares/total                    774
winShares/totalPer40               774
dtype: int64
Duplicate rows: 0

Missing data for 2022:

                       Missing Count  Missing Percentage
conference                      4304               45.79
assistsTurnoverRatio            1801               19.16
offensiveReboundPct             1262               13.43
netRating                        774                8.23
winShares/totalPer40             774                8.23
winShares/total                  774                8.23
winShares/offensive              772                8.21
PORPAG                           669                7.12
offensiveRating                  667                7.10
freeThrowRate                    622                6.62
effectiveFieldGoalPct            622                6.62
trueShootingPct                  548                5.83
defensiveRating                  152                1.62
winShares/defensive              152                1.62
usage                             22                0.23
position                           5                0.05

========================================
Player Stats 2023
<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9752 non-null   int64
 1   seasonLabel                     9752 non-null   int64
 2   teamId                          9752 non-null   int64
 3   team                            9752 non-null   str
 4   conference                      5102 non-null   str
 5   athleteId                       9752 non-null   int64
 6   athleteSourceId                 9752 non-null   int64
 7   name                            9752 non-null   str
 8   position                        9750 non-null   str
 9   games                           9752 non-null   int64
 10  starts                          9752 non-null   int64
 11  minutes                         9752 non-null   int64
 12  points                          9752 non-null   int64
 13  turnovers                       9752 non-null   int64
 14  fouls                           9752 non-null   int64
 15  assists                         9752 non-null   int64
 16  steals                          9752 non-null   int64
 17  blocks                          9752 non-null   int64
 18  offensiveRating                 9024 non-null   float64
 19  defensiveRating                 9591 non-null   float64
 20  netRating                       8925 non-null   float64
 21  PORPAG                          9024 non-null   float64
 22  usage                           9717 non-null   float64
 23  assistsTurnoverRatio            7848 non-null   float64
 24  offensiveReboundPct             8431 non-null   float64
 25  freeThrowRate                   9058 non-null   float64
 26  effectiveFieldGoalPct           9058 non-null   float64
 27  trueShootingPct                 9138 non-null   float64
 28  fieldGoals/made                 9752 non-null   int64
 29  fieldGoals/attempted            9752 non-null   int64
 30  fieldGoals/pct                  9752 non-null   float64
 31  twoPointFieldGoals/made         9752 non-null   int64
 32  twoPointFieldGoals/attempted    9752 non-null   int64
 33  twoPointFieldGoals/pct          9752 non-null   float64
 34  threePointFieldGoals/made       9752 non-null   int64
 35  threePointFieldGoals/attempted  9752 non-null   int64
 36  threePointFieldGoals/pct        9752 non-null   float64
 37  freeThrows/made                 9752 non-null   int64
 38  freeThrows/attempted            9752 non-null   int64
 39  freeThrows/pct                  9752 non-null   float64
 40  rebounds/offensive              9752 non-null   int64
 41  rebounds/defensive              9752 non-null   int64
 42  rebounds/total                  9752 non-null   int64
 43  winShares/offensive             8925 non-null   float64
 44  winShares/defensive             9591 non-null   float64
 45  winShares/total                 8925 non-null   float64
 46  winShares/totalPer40            8925 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4650
athleteId                            0
athleteSourceId                      0
name                                 0
position                             2
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    728
defensiveRating                    161
netRating                          827
PORPAG                             728
usage                               35
assistsTurnoverRatio              1904
offensiveReboundPct               1321
freeThrowRate                      694
effectiveFieldGoalPct              694
trueShootingPct                    614
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                827
winShares/defensive                161
winShares/total                    827
winShares/totalPer40               827
dtype: int64
Duplicate rows: 0

Missing data for 2023:

                       Missing Count  Missing Percentage
conference                      4650               47.68
assistsTurnoverRatio            1904               19.52
offensiveReboundPct             1321               13.55
netRating                        827                8.48
winShares/offensive              827                8.48
winShares/total                  827                8.48
winShares/totalPer40             827                8.48
offensiveRating                  728                7.47
PORPAG                           728                7.47
freeThrowRate                    694                7.12
effectiveFieldGoalPct            694                7.12
trueShootingPct                  614                6.30
defensiveRating                  161                1.65
winShares/defensive              161                1.65
usage                             35                0.36
position                           2                0.02

========================================
Player Stats 2024
<class 'pandas.DataFrame'>
RangeIndex: 9861 entries, 0 to 9860
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9861 non-null   int64
 1   seasonLabel                     9861 non-null   int64
 2   teamId                          9861 non-null   int64
 3   team                            9861 non-null   str
 4   conference                      5063 non-null   str
 5   athleteId                       9861 non-null   int64
 6   athleteSourceId                 9861 non-null   int64
 7   name                            9861 non-null   str
 8   position                        9861 non-null   str
 9   games                           9861 non-null   int64
 10  starts                          9861 non-null   int64
 11  minutes                         9861 non-null   int64
 12  points                          9861 non-null   int64
 13  turnovers                       9861 non-null   int64
 14  fouls                           9861 non-null   int64
 15  assists                         9861 non-null   int64
 16  steals                          9861 non-null   int64
 17  blocks                          9861 non-null   int64
 18  offensiveRating                 9189 non-null   float64
 19  defensiveRating                 9786 non-null   float64
 20  netRating                       9145 non-null   float64
 21  PORPAG                          9189 non-null   float64
 22  usage                           9839 non-null   float64
 23  assistsTurnoverRatio            7786 non-null   float64
 24  offensiveReboundPct             8566 non-null   float64
 25  freeThrowRate                   9222 non-null   float64
 26  effectiveFieldGoalPct           9222 non-null   float64
 27  trueShootingPct                 9299 non-null   float64
 28  fieldGoals/made                 9861 non-null   int64
 29  fieldGoals/attempted            9861 non-null   int64
 30  fieldGoals/pct                  9861 non-null   float64
 31  twoPointFieldGoals/made         9861 non-null   int64
 32  twoPointFieldGoals/attempted    9861 non-null   int64
 33  twoPointFieldGoals/pct          9861 non-null   float64
 34  threePointFieldGoals/made       9861 non-null   int64
 35  threePointFieldGoals/attempted  9861 non-null   int64
 36  threePointFieldGoals/pct        9861 non-null   float64
 37  freeThrows/made                 9861 non-null   int64
 38  freeThrows/attempted            9861 non-null   int64
 39  freeThrows/pct                  9861 non-null   float64
 40  rebounds/offensive              9861 non-null   int64
 41  rebounds/defensive              9861 non-null   int64
 42  rebounds/total                  9861 non-null   int64
 43  winShares/offensive             9146 non-null   float64
 44  winShares/defensive             9786 non-null   float64
 45  winShares/total                 9145 non-null   float64
 46  winShares/totalPer40            9145 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4798
athleteId                            0
athleteSourceId                      0
name                                 0
position                             0
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    672
defensiveRating                     75
netRating                          716
PORPAG                             672
usage                               22
assistsTurnoverRatio              2075
offensiveReboundPct               1295
freeThrowRate                      639
effectiveFieldGoalPct              639
trueShootingPct                    562
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                715
winShares/defensive                 75
winShares/total                    716
winShares/totalPer40               716
dtype: int64
Duplicate rows: 0

Missing data for 2024:

                       Missing Count  Missing Percentage
conference                      4798               48.66
assistsTurnoverRatio            2075               21.04
offensiveReboundPct             1295               13.13
winShares/totalPer40             716                7.26
winShares/total                  716                7.26
netRating                        716                7.26
winShares/offensive              715                7.25
offensiveRating                  672                6.81
PORPAG                           672                6.81
freeThrowRate                    639                6.48
effectiveFieldGoalPct            639                6.48
trueShootingPct                  562                5.70
defensiveRating                   75                0.76
winShares/defensive               75                0.76
usage                             22                0.22

========================================
Player Stats 2025
<class 'pandas.DataFrame'>
RangeIndex: 9808 entries, 0 to 9807
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9808 non-null   int64
 1   seasonLabel                     9808 non-null   int64
 2   teamId                          9808 non-null   int64
 3   team                            9808 non-null   str
 4   conference                      5144 non-null   str
 5   athleteId                       9808 non-null   int64
 6   athleteSourceId                 9808 non-null   int64
 7   name                            9808 non-null   str
 8   position                        9786 non-null   str
 9   games                           9808 non-null   int64
 10  starts                          9808 non-null   int64
 11  minutes                         9808 non-null   int64
 12  points                          9808 non-null   int64
 13  turnovers                       9808 non-null   int64
 14  fouls                           9808 non-null   int64
 15  assists                         9808 non-null   int64
 16  steals                          9808 non-null   int64
 17  blocks                          9808 non-null   int64
 18  offensiveRating                 9130 non-null   float64
 19  defensiveRating                 9495 non-null   float64
 20  netRating                       8889 non-null   float64
 21  PORPAG                          9130 non-null   float64
 22  usage                           9771 non-null   float64
 23  assistsTurnoverRatio            7785 non-null   float64
 24  offensiveReboundPct             8470 non-null   float64
 25  freeThrowRate                   9156 non-null   float64
 26  effectiveFieldGoalPct           9156 non-null   float64
 27  trueShootingPct                 9260 non-null   float64
 28  fieldGoals/made                 9808 non-null   int64
 29  fieldGoals/attempted            9808 non-null   int64
 30  fieldGoals/pct                  9808 non-null   float64
 31  twoPointFieldGoals/made         9808 non-null   int64
 32  twoPointFieldGoals/attempted    9808 non-null   int64
 33  twoPointFieldGoals/pct          9808 non-null   float64
 34  threePointFieldGoals/made       9808 non-null   int64
 35  threePointFieldGoals/attempted  9808 non-null   int64
 36  threePointFieldGoals/pct        9808 non-null   float64
 37  freeThrows/made                 9808 non-null   int64
 38  freeThrows/attempted            9808 non-null   int64
 39  freeThrows/pct                  9808 non-null   float64
 40  rebounds/offensive              9808 non-null   int64
 41  rebounds/defensive              9808 non-null   int64
 42  rebounds/total                  9808 non-null   int64
 43  winShares/offensive             8889 non-null   float64
 44  winShares/defensive             9495 non-null   float64
 45  winShares/total                 8889 non-null   float64
 46  winShares/totalPer40            8889 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4664
athleteId                            0
athleteSourceId                      0
name                                 0
position                            22
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    678
defensiveRating                    313
netRating                          919
PORPAG                             678
usage                               37
assistsTurnoverRatio              2023
offensiveReboundPct               1338
freeThrowRate                      652
effectiveFieldGoalPct              652
trueShootingPct                    548
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                919
winShares/defensive                313
winShares/total                    919
winShares/totalPer40               919
dtype: int64
Duplicate rows: 0

Missing data for 2025:

                       Missing Count  Missing Percentage
conference                      4664               47.55
assistsTurnoverRatio            2023               20.63
offensiveReboundPct             1338               13.64
netRating                        919                9.37
winShares/offensive              919                9.37
winShares/total                  919                9.37
winShares/totalPer40             919                9.37
offensiveRating                  678                6.91
PORPAG                           678                6.91
freeThrowRate                    652                6.65
effectiveFieldGoalPct            652                6.65
trueShootingPct                  548                5.59
defensiveRating                  313                3.19
winShares/defensive              313                3.19
usage                             37                0.38
position                          22                0.22

========================================
Player Stats 2026
<class 'pandas.DataFrame'>
RangeIndex: 10030 entries, 0 to 10029
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          10030 non-null  int64
 1   seasonLabel                     10030 non-null  int64
 2   teamId                          10030 non-null  int64
 3   team                            10030 non-null  str
 4   conference                      5035 non-null   str
 5   athleteId                       10030 non-null  int64
 6   athleteSourceId                 10030 non-null  int64
 7   name                            10030 non-null  str
 8   position                        10029 non-null  str
 9   games                           10030 non-null  int64
 10  starts                          10030 non-null  int64
 11  minutes                         10030 non-null  int64
 12  points                          10030 non-null  int64
 13  turnovers                       10030 non-null  int64
 14  fouls                           10030 non-null  int64
 15  assists                         10030 non-null  int64
 16  steals                          10030 non-null  int64
 17  blocks                          10030 non-null  int64
 18  offensiveRating                 9383 non-null   float64
 19  defensiveRating                 9922 non-null   float64
 20  netRating                       9311 non-null   float64
 21  PORPAG                          9382 non-null   float64
 22  usage                           9999 non-null   float64
 23  assistsTurnoverRatio            7962 non-null   float64
 24  offensiveReboundPct             8627 non-null   float64
 25  freeThrowRate                   9385 non-null   float64
 26  effectiveFieldGoalPct           9385 non-null   float64
 27  trueShootingPct                 9455 non-null   float64
 28  fieldGoals/made                 10030 non-null  int64
 29  fieldGoals/attempted            10030 non-null  int64
 30  fieldGoals/pct                  10030 non-null  float64
 31  twoPointFieldGoals/made         10030 non-null  int64
 32  twoPointFieldGoals/attempted    10030 non-null  int64
 33  twoPointFieldGoals/pct          10030 non-null  float64
 34  threePointFieldGoals/made       10030 non-null  int64
 35  threePointFieldGoals/attempted  10030 non-null  int64
 36  threePointFieldGoals/pct        10030 non-null  float64
 37  freeThrows/made                 10030 non-null  int64
 38  freeThrows/attempted            10030 non-null  int64
 39  freeThrows/pct                  10030 non-null  float64
 40  rebounds/offensive              10030 non-null  int64
 41  rebounds/defensive              10030 non-null  int64
 42  rebounds/total                  10030 non-null  int64
 43  winShares/offensive             9312 non-null   float64
 44  winShares/defensive             9922 non-null   float64
 45  winShares/total                 9311 non-null   float64
 46  winShares/totalPer40            9311 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.6 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        4995
athleteId                            0
athleteSourceId                      0
name                                 0
position                             1
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    647
defensiveRating                    108
netRating                          719
PORPAG                             648
usage                               31
assistsTurnoverRatio              2068
offensiveReboundPct               1403
freeThrowRate                      645
effectiveFieldGoalPct              645
trueShootingPct                    575
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                718
winShares/defensive                108
winShares/total                    719
winShares/totalPer40               719
dtype: int64
Duplicate rows: 0

Missing data for 2026:

                       Missing Count  Missing Percentage
conference                      4995               49.80
assistsTurnoverRatio            2068               20.62
offensiveReboundPct             1403               13.99
netRating                        719                7.17
winShares/totalPer40             719                7.17
winShares/total                  719                7.17
winShares/offensive              718                7.16
PORPAG                           648                6.46
offensiveRating                  647                6.45
freeThrowRate                    645                6.43
effectiveFieldGoalPct            645                6.43
trueShootingPct                  575                5.73
defensiveRating                  108                1.08
winShares/defensive              108                1.08
usage                             31                0.31
position                           1                0.01

In [31]:
#preparing/cleaning
all_stats = pd.concat(
    [
        df.assign(dataset_year=int(year))
        for year, df in datasets.items()
    ],
    ignore_index=True
)

missing_conf = all_stats[all_stats["conference"].isna()]

missing_schools = (
    missing_conf.groupby(["dataset_year", "team"])
    .size()
    .reset_index(name="players_missing_conference")
    .sort_values(
        ["dataset_year", "players_missing_conference"],
        ascending=[True, False]
    )
)

school_conferences = (
    all_stats[all_stats["conference"].notna()]
    .groupby("team")["conference"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index(name="conferences_found")
)

missing_schools_check = missing_schools.merge(
    school_conferences,
    on="team",
    how="left"
)

display(missing_schools_check)

,dataset_year,team,players_missing_conference,conferences_found
0,2020,Lindenwood,24,[OVC]
1,2020,Carver College,23,NaN
2,2020,Bethesda University,22,NaN
3,2020,Misericordia,22,NaN
4,2020,Westcliff,21,NaN
...,...,...,...,...
2146,2026,Rust,8,NaN
2147,2026,Kean,7,NaN
2148,2026,Maine-Fort Kent,7,NaN
2149,2026,Williams Baptist,7,NaN
2150,2026,Regis (CO),6,NaN

In [30]:

import requests
import pandas as pd

base_url = "https://web3.ncaa.org/directory/api/directory/memberList"

def get_schools(division):
    params = {
        "type": 12,
        "division": division,
        "sportCode": "MBB"
    }

    response = requests.get(base_url, params=params, timeout=30)
    response.raise_for_status()

    df = pd.DataFrame(response.json())

    df = df[["nameOfficial", "division", "conferenceName"]].copy()
    df.columns = ["school_name", "division_number", "conference"]

    df["division_label"] = df["division_number"].map({
        2: "D2",
        3: "D3"
    })

    expected_number = {"II": 2, "III": 3}[division]
    df = df[df["division_number"] == expected_number].copy()

    return df[["school_name", "division_label", "conference"]]

d2_df = get_schools("II")
d3_df = get_schools("III")

schools_df = pd.concat([d2_df, d3_df], ignore_index=True)

print(schools_df.head(10))
print("\nSchools by division:")
print(schools_df.groupby("division_label").size())

assert set(schools_df["division_label"].dropna()) == {"D2", "D3"}

schools_df.to_csv("data/ncaa_d2_d3_mens_basketball.csv", index=False)
print("\nSaved NCAA Division II and III school reference.")

                            school_name division_label  \
0                Adams State University             D2
1                    Adelphi University             D2
2   University of Alabama in Huntsville             D2
3        University of Alaska Anchorage             D2
4        University of Alaska Fairbanks             D2
5     Albany State University (Georgia)             D2
6                      Allen University             D2
7        American International College             D2
8  Anderson University (South Carolina)             D2
9               Angelo State University             D2

                            conference
0   Rocky Mountain Athletic Conference
1              Northeast 10 Conference
2                Gulf South Conference
3  Great Northwest Athletic Conference
4  Great Northwest Athletic Conference
5        Southern Intercol. Ath. Conf.
6        Southern Intercol. Ath. Conf.
7              Northeast 10 Conference
8            South Atlantic Conference
9                 Lone Star Conference

Schools by division:
division_label
D2    298
D3    406
dtype: int64

Saved NCAA Division II and III school reference.

In [5]:
import pandas as pd
from pathlib import Path

ncaa = pd.read_csv(DATA_DIR / "ncaa_d2_d3_mens_basketball.csv")

def normalize(name):
    return (str(name).lower().strip().replace(".", "").replace(",", "").replace("(", "").replace(")", "").replace("-", " ").split())

def school_key(name):
    return " ".join(normalize(name))

ncaa["school_key"] = ncaa["school_name"].fillna("").apply(school_key)
division_map = ncaa.set_index("school_key")["division_label"].to_dict()

file = DATA_DIR / "player_stats_2020.csv"
df = pd.read_csv(file)

missing = (df["conference"].isna() | df["conference"].astype(str).str.strip().eq(""))

name_overrides = {
    "Centenary (LA)": "Centenary College (Louisiana)",
    "Erskine": "Erskine College",
    "Washington College (MD)": "Washington College (Maryland)",
    "Georgian Court": "Georgian Court University",
    "Piedmont": "Piedmont University",
    "NC Wesleyan": "North Carolina Wesleyan University",
    "William Peace": "William Peace University",
    "Vermont State - Lyndon": "Vermont State University Lyndon",
    "Newberry": "Newberry College",
    "Pfeiffer": "Pfeiffer University",
    "Western Colorado": "Western Colorado University",
    "Maryville College (TN)": "Maryville College (Tennessee)",
    "Trinity (TX)": "Trinity University (Texas)",
    "Western New Mexico": "Western New Mexico University",
    "Howard Payne": "Howard Payne University",
    "Nebraska Wesleyan": "Nebraska Wesleyan University",
    "Widener": "Widener University",
    "Concordia-Chicago": "Concordia University Chicago",
    "Central State Oklahoma": "University of Central Oklahoma",
    "Nebraska-Kearney": "University of Nebraska at Kearney",
    "Carson-Newman": "Carson-Newman University",
    "Missouri-St. Louis": "University of Missouri-St. Louis",
    "East Central (OK)": "East Central University",
    "Geneva": "Geneva College",
    "Caldwell": "Caldwell University",
    "Maine Maritime": "Maine Maritime Academy",
    "Ohio Northern": "Ohio Northern University",
    "Arkansas Tech": "Arkansas Tech University",
    "Cortland": "State University of New York at Cortland",
    "CS San Bernardino": "California State University, San Bernardino",
    "Southwest Baptist": "Southwest Baptist University",
    "Wisconsin-Lutheran": "Wisconsin Lutheran College",
    "Tampa": "University of Tampa",
    "Gettysburg": "Gettysburg College",
    "Hampden-Sydney": "Hampden-Sydney College",
    "Chicago": "University of Chicago",
    "Arkansas-Monticello": "University of Arkansas, Monticello",
    "New Mexico Highlands": "New Mexico Highlands University",
    "San Francisco State": "San Francisco State University",
    "Davenport": "Davenport University",
    "Colorado Christian": "Colorado Christian University",
    "UT Permian Basin": "The University of Texas Permian Basin",
    "Texas Permian Basin": "The University of Texas Permian Basin",
    "North Greenville": "North Greenville University",
    "Central State (OH)": "Central State University",
    "Stanislaus State": "California State University, Stanislaus",
    "Florida Tech": "Florida Institute of Technology",
    "Rogers State": "Rogers State University",
    "Hawai’i Pacific": "Hawaii Pacific University",
    "Kentucky Wesleyan": "Kentucky Wesleyan College",
    "UVA Wise": "The University of Virginia's College at Wise",
    "Morehouse": "Morehouse College",
    "Malone": "Malone University",
    "Delta State": "Delta State University",
    "Fresno Pacific": "Fresno Pacific University",
    #shut down "Sonoma State": "",
    "Tiffin": "Tiffin University",
    "Chaminade": "Chaminade University",
    "Montevallo": "University of Montevallo",
    "E. New Mexico": "Eastern New Mexico University",
    "Coker": "Coker University",
    "Trevecca Nazarene": "Trevecca Nazarene University",
    "Illinois-Springfield": "University of Illinois Springfield",
    "Shorter": "Shorter University",
    "Missouri S&T": "Missouri University of Science and Technology",
    "St. Mary's (TX)": "St. Mary's University (Texas)",
    #"Tennessee Southern": "",
    "Mars Hill": "Mars Hill University",
    #closed "Holy Names": "",
    "Concord": "Concord University",
    "Fairmont St": "Fairmont State University",
    "Cal State LA": "California State University, Los Angeles",
    "Texas A&M-International": "Texas A&M International University",
    "Oklahoma Christian": "Oklahoma Christian University",
    "Edinboro": "Pennsylvania Western University, Edinboro",
    "Palm Beach Atlantic": "Palm Beach Atlantic University",
    "Quincy": "Quincy University",
    "Maryville (MO)": "Maryville University of Saint Louis",
    "Gannon": "Gannon University",
    "Belmont Abbey": "Belmont Abbey College",
    "Purdue Northwest": "Purdue University Northwest",
    "McKendree": "McKendree University",
    "Bluefield State": "Bluefield State University",
    #"Olivet Nazarene": "",
    #closed "Notre Dame de Namur": "",
    #"New York Institute of Technology": "",
    #"Urbana": "",
    #closed in 2024 "Birmingham-Southern": "",
    #"Defiance": "",
    "Westminster (PA)": "Westminster College (Pennsylvania)",
    "Massachusetts-Boston": "University of Massachusetts Boston",
    "SUNY-Oneonta": "State University of New York at Oneonta",
    "Eureka": "Eureka College",
    "Purchase": "Purchase College, State University of New York",
    "UT Dallas": "University of Texas at Dallas",
    "Southwestern (TX)": "Southwestern University (Texas)",
    "SUNY Poly": "State University of New York Polytechnic Institute",
    "LeTourneau": "LeTourneau University",
    "Rhodes": "Rhodes College",
    "Emerson": "Emerson College",
    "Misericordia": "Misericordia University",
    "Rockford": "Rockford University",
    "Gallaudet": "Gallaudet University",
    "Saint Elizabeth": "Saint Elizabeth University",
    "Ferrum": "Ferrum College",
    #"Rosemont": "",
    "Texas Lutheran": "Texas Lutheran University",
    "Nazareth College": "Nazareth University",
    "Averett": "Averett University",
    "Regent": "Regent University",
    "Brevard": "Brevard College",
    "Merchant Marine Academy": "U.S. Merchant Marine Academy",
    "Thomas (ME)": "Thomas College",
    "Wisconsin-Stout": "University of Wisconsin-Stout Polytechnic",
    #"Bryn Athyn": "",
    "Pacific (OR)": "Pacific University (Oregon)",
    "Crown College": "Crown College (Minnesota)",
    "St. Thomas (TX)": "University of St. Thomas (Texas)",
    "Whittier": "",
    "Willamette": "Whittier College",
    "Johnson & Wales (RI)": "Johnson & Wales University (Providence)",
    "Johnson & Wales (NC)": "Johnson & Wales University Charlotte", #closed in 2021?
    "Heidelberg": "Heidelberg University",
    #"Benedictine (AZ)": "",
    "Anderson (IN)": "Anderson University (Indiana)",
    "Kean": "Kean University",
    "Medgar Evers": "Medgar Evers College",
    "Spalding": "Spalding University",
    "Millsaps": "Millsaps College",
    "North Park": "North Park University",
    "St. Mary’s (MD)": "St. Mary's College of Maryland",
    "Luther": "Luther College",
    "Pacific Lutheran": "Pacific Lutheran University",
    #"Northland": "",
    "SUNY-Potsdam": "State University of New York at Potsdam",
    "FDU Florham": "Fairleigh Dickinson University, Florham",
    "Bridgewater College (VA)": "",
    "Mount Saint Vincent": "University of Mount Saint Vincent",
    "Emory & Henry": "Emory & Henry University",
    "Puget Sound": "University of Puget Sound",
    "Manchester": "Manchester University",
    "Alma": "Alma College",
    "Mount St. Joseph": "Mount St. Joseph University",
    "Goucher": "Goucher College",
    "Centenary (NJ)": "Centenary University (New Jersey)",
    "Rutgers-Camden": "Rutgers, The State Univ. of New Jersey, Camden",
    "Shenandoah": "Shenandoah University",
    "Oberlin": "Oberlin College",
    "Concordia-Texas": "Concordia University Texas",
    "MIT": "Massachusetts Institute of Technology",
    "Elizabethtown": "Elizabethtown College",
    "Hartwick": "Hartwick College",
    "Cal Lutheran": "California Lutheran University",
    "Redlands": "University of Redlands",
    "Farmingdale State": "Farmingdale State College",
    "Elmira": "Elmira College",
    "Flagler": "Flagler College",
    "East Texas Baptist": "East Texas Baptist University",
    "Cornell College (IA)": "Cornell College",
    "Simpson College (IA)": "Simpson College",
    "Marymount (VA)": "Marymount University (Virginia)",
    "Thiel": "Thiel College",
    "Concordia (WI)": "Concordia University Wisconsin",
    "Illinois Wesleyan": "Illinois Wesleyan University",
    "UC Santa Cruz": "University of California, Santa Cruz",
    "Hiram": "Hiram College",
    #"Wesley": "",
    #merged into Boston College in 2021 "Pine Manor": ""
}

school_names = df["team"].fillna("").astype(str).replace(name_overrides)
school_keys = school_names.apply(school_key)

matched_division = school_keys.map(division_map)
update = missing & matched_division.isin(["D2", "D3"])

df.loc[update, "conference"] = matched_division[update]
df.to_csv(file, index=False)

print(f"2020: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df.loc[missing & ~update, "team"].dropna().unique()[:])

2020: filled 856 missing conferences

Still missing schools:
<StringArray>
[                      'Lindenwood',              'Birmingham-Southern',
                  'Penn State-York',              'Alice Lloyd College',
                         'Defiance',           'Mid-Atlantic Christian',
           'Columbia International',                  'Trinity Baptist',
                        'Bob Jones',                 'Dallas Christian',
 ...
                        'Pikeville',                           'Wesley',
                 'Ohio-Chillicothe', 'New York Institute Of Technology',
                           'Urbana',                       'Pine Manor',
                       'Rio Grande',                     'Bethany (KS)',
             'Johnson & Wales (CO)',                      'Thomas (GA)']
Length: 150, dtype: str

## Explore data

In [ ]:
# Summarize and visualize the prepared data.

## Build models

In [ ]:
# Train baseline and candidate models.

## Evaluate models

In [ ]:
# Compare models using the chosen evaluation measures.

## Final results

In [ ]:
# Generate the final tables and figures.

## AI usage disclosure

- **AI tool/model:** [Name the tool and model, or state that no generative AI was used.]
- **Used for:** [Briefly identify the tasks.]
- **How we verified the work:** [Briefly identify the checks.]
- **Prompt(s) used:** [Paste the prompts used.]