# Predicting Division I Men's Basketball Transfer Portal Starters

**Team members:** Aurea McIntosh, Zoe Edelblum, Evie McMahan 

**Repository:** https://github.com/eviemcmahan/ds_3001_project_team_6.git

## Setup

Use relative paths and keep the notebook runnable from beginning to end.

In [33]:
from pathlib import Path

DATA_DIR = Path("data")
assert DATA_DIR.is_dir(), "The data directory is missing."

## Load data

In [34]:
# Load data from DATA_DIR.
!pip install pandas
import pandas as pd

espn_rankings = pd.read_csv(DATA_DIR / "espn_preseason_rankings.csv")
player_stats_2020 = pd.read_csv(DATA_DIR / "player_stats_2020.csv")
player_stats_2021 = pd.read_csv(DATA_DIR / "player_stats_2021.csv")
player_stats_2022 = pd.read_csv(DATA_DIR / "player_stats_2022.csv")
player_stats_2023 = pd.read_csv(DATA_DIR / "player_stats_2023.csv")
player_stats_2024 = pd.read_csv(DATA_DIR / "player_stats_2024.csv")
player_stats_2025 = pd.read_csv(DATA_DIR / "player_stats_2025.csv")
player_stats_2026 = pd.read_csv(DATA_DIR / "player_stats_2026.csv")

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python3 -m pip install --upgrade pip

## Prepare data

In [35]:
# Clean data and create features.
espn_rankings.info()
print("Missing values:\n", espn_rankings.isna().sum())
print("Duplicate rows:", espn_rankings.duplicated().sum())

datasets = {
    "2020": player_stats_2020,
    "2021": player_stats_2021,
    "2022": player_stats_2022,
    "2023": player_stats_2023,
    "2024": player_stats_2024,
    "2025": player_stats_2025,
    "2026": player_stats_2026,
}

for year, df in datasets.items():
    print(f"\n{'=' * 40}\nPlayer Stats {year}")
    df.info()
    print("Missing values:\n", df.isna().sum())
    print("Duplicate rows:", df.duplicated().sum())

    missing = df.isna().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        "Missing Count": missing,
        "Missing Percentage": missing_pct
    })

    missing_summary = missing_summary[
        missing_summary["Missing Count"] > 0
    ].sort_values("Missing Percentage", ascending=False)

    print(f"\nMissing data for {year}:")
    display(missing_summary)

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   season               600 non-null    str
 1   year                 600 non-null    int64
 2   espn_preseason_rank  600 non-null    int64
 3   player               600 non-null    str
 4   player_key           600 non-null    str
 5   espn_player_id       597 non-null    float64
 6   height_in            600 non-null    int64
 7   position             599 non-null    str
 8   class_prev_season    599 non-null    str
 9   prev_school          600 non-null    str
 10  new_school           600 non-null    str
dtypes: float64(1), int64(3), str(7)
memory usage: 51.7 KB
Missing values:
 season                 0
year                   0
espn_preseason_rank    0
player                 0
player_key             0
espn_player_id         3
height_in              0
position               1
class_prev_season      1
prev_school            0
new_school             0
dtype: int64
Duplicate rows: 0

========================================
Player Stats 2020
<class 'pandas.DataFrame'>
RangeIndex: 8835 entries, 0 to 8834
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          8835 non-null   int64
 1   seasonLabel                     8835 non-null   int64
 2   teamId                          8835 non-null   int64
 3   team                            8835 non-null   str
 4   conference                      6902 non-null   str
 5   athleteId                       8835 non-null   int64
 6   athleteSourceId                 8835 non-null   int64
 7   name                            8835 non-null   str
 8   position                        8826 non-null   str
 9   games                           8835 non-null   int64
 10  starts                          8835 non-null   int64
 11  minutes                         8835 non-null   int64
 12  points                          8835 non-null   int64
 13  turnovers                       8835 non-null   int64
 14  fouls                           8835 non-null   int64
 15  assists                         8835 non-null   int64
 16  steals                          8835 non-null   int64
 17  blocks                          8835 non-null   int64
 18  offensiveRating                 8240 non-null   float64
 19  defensiveRating                 8346 non-null   float64
 20  netRating                       7856 non-null   float64
 21  PORPAG                          8239 non-null   float64
 22  usage                           8782 non-null   float64
 23  assistsTurnoverRatio            7176 non-null   float64
 24  offensiveReboundPct             7654 non-null   float64
 25  freeThrowRate                   8245 non-null   float64
 26  effectiveFieldGoalPct           8245 non-null   float64
 27  trueShootingPct                 8321 non-null   float64
 28  fieldGoals/made                 8835 non-null   int64
 29  fieldGoals/attempted            8835 non-null   int64
 30  fieldGoals/pct                  8835 non-null   float64
 31  twoPointFieldGoals/made         8835 non-null   int64
 32  twoPointFieldGoals/attempted    8835 non-null   int64
 33  twoPointFieldGoals/pct          8835 non-null   float64
 34  threePointFieldGoals/made       8835 non-null   int64
 35  threePointFieldGoals/attempted  8835 non-null   int64
 36  threePointFieldGoals/pct        8835 non-null   float64
 37  freeThrows/made                 8835 non-null   int64
 38  freeThrows/attempted            8835 non-null   int64
 39  freeThrows/pct                  8835 non-null   float64
 40  rebounds/offensive              8835 non-null   int64
 41  rebounds/defensive              8835 non-null   int64
 42  rebounds/total                  8835 non-null   int64
 43  winShares/offensive             7881 non-null   float64
 44  winShares/defensive             8346 non-null   float64
 45  winShares/total                 7856 non-null   float64
 46  winShares/totalPer40            7856 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.2 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        1933
athleteId                            0
athleteSourceId                      0
name                                 0
position                             9
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    595
defensiveRating                    489
netRating                          979
PORPAG                             596
usage                               53
assistsTurnoverRatio              1659
offensiveReboundPct               1181
freeThrowRate                      590
effectiveFieldGoalPct              590
trueShootingPct                    514
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                954
winShares/defensive                489
winShares/total                    979
winShares/totalPer40               979
dtype: int64
Duplicate rows: 0

Missing data for 2020:

                       Missing Count  Missing Percentage
conference                      1933               21.88
assistsTurnoverRatio            1659               18.78
offensiveReboundPct             1181               13.37
netRating                        979               11.08
winShares/totalPer40             979               11.08
winShares/total                  979               11.08
winShares/offensive              954               10.80
PORPAG                           596                6.75
offensiveRating                  595                6.73
freeThrowRate                    590                6.68
effectiveFieldGoalPct            590                6.68
trueShootingPct                  514                5.82
defensiveRating                  489                5.53
winShares/defensive              489                5.53
usage                             53                0.60
position                           9                0.10

========================================
Player Stats 2021
<class 'pandas.DataFrame'>
RangeIndex: 9861 entries, 0 to 9860
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9861 non-null   int64
 1   seasonLabel                     9861 non-null   int64
 2   teamId                          9861 non-null   int64
 3   team                            9861 non-null   str
 4   conference                      6079 non-null   str
 5   athleteId                       9861 non-null   int64
 6   athleteSourceId                 9861 non-null   int64
 7   name                            9861 non-null   str
 8   position                        9861 non-null   str
 9   games                           9861 non-null   int64
 10  starts                          9861 non-null   int64
 11  minutes                         9861 non-null   int64
 12  points                          9861 non-null   int64
 13  turnovers                       9861 non-null   int64
 14  fouls                           9861 non-null   int64
 15  assists                         9861 non-null   int64
 16  steals                          9861 non-null   int64
 17  blocks                          9861 non-null   int64
 18  offensiveRating                 9189 non-null   float64
 19  defensiveRating                 9786 non-null   float64
 20  netRating                       9145 non-null   float64
 21  PORPAG                          9189 non-null   float64
 22  usage                           9839 non-null   float64
 23  assistsTurnoverRatio            7786 non-null   float64
 24  offensiveReboundPct             8566 non-null   float64
 25  freeThrowRate                   9222 non-null   float64
 26  effectiveFieldGoalPct           9222 non-null   float64
 27  trueShootingPct                 9299 non-null   float64
 28  fieldGoals/made                 9861 non-null   int64
 29  fieldGoals/attempted            9861 non-null   int64
 30  fieldGoals/pct                  9861 non-null   float64
 31  twoPointFieldGoals/made         9861 non-null   int64
 32  twoPointFieldGoals/attempted    9861 non-null   int64
 33  twoPointFieldGoals/pct          9861 non-null   float64
 34  threePointFieldGoals/made       9861 non-null   int64
 35  threePointFieldGoals/attempted  9861 non-null   int64
 36  threePointFieldGoals/pct        9861 non-null   float64
 37  freeThrows/made                 9861 non-null   int64
 38  freeThrows/attempted            9861 non-null   int64
 39  freeThrows/pct                  9861 non-null   float64
 40  rebounds/offensive              9861 non-null   int64
 41  rebounds/defensive              9861 non-null   int64
 42  rebounds/total                  9861 non-null   int64
 43  winShares/offensive             9146 non-null   float64
 44  winShares/defensive             9786 non-null   float64
 45  winShares/total                 9145 non-null   float64
 46  winShares/totalPer40            9145 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3782
athleteId                            0
athleteSourceId                      0
name                                 0
position                             0
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    672
defensiveRating                     75
netRating                          716
PORPAG                             672
usage                               22
assistsTurnoverRatio              2075
offensiveReboundPct               1295
freeThrowRate                      639
effectiveFieldGoalPct              639
trueShootingPct                    562
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                715
winShares/defensive                 75
winShares/total                    716
winShares/totalPer40               716
dtype: int64
Duplicate rows: 0

Missing data for 2021:

                       Missing Count  Missing Percentage
conference                      3782               38.35
assistsTurnoverRatio            2075               21.04
offensiveReboundPct             1295               13.13
winShares/totalPer40             716                7.26
winShares/total                  716                7.26
netRating                        716                7.26
winShares/offensive              715                7.25
offensiveRating                  672                6.81
PORPAG                           672                6.81
freeThrowRate                    639                6.48
effectiveFieldGoalPct            639                6.48
trueShootingPct                  562                5.70
defensiveRating                   75                0.76
winShares/defensive               75                0.76
usage                             22                0.22

========================================
Player Stats 2022
<class 'pandas.DataFrame'>
RangeIndex: 9861 entries, 0 to 9860
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9861 non-null   int64
 1   seasonLabel                     9861 non-null   int64
 2   teamId                          9861 non-null   int64
 3   team                            9861 non-null   str
 4   conference                      6079 non-null   str
 5   athleteId                       9861 non-null   int64
 6   athleteSourceId                 9861 non-null   int64
 7   name                            9861 non-null   str
 8   position                        9861 non-null   str
 9   games                           9861 non-null   int64
 10  starts                          9861 non-null   int64
 11  minutes                         9861 non-null   int64
 12  points                          9861 non-null   int64
 13  turnovers                       9861 non-null   int64
 14  fouls                           9861 non-null   int64
 15  assists                         9861 non-null   int64
 16  steals                          9861 non-null   int64
 17  blocks                          9861 non-null   int64
 18  offensiveRating                 9189 non-null   float64
 19  defensiveRating                 9786 non-null   float64
 20  netRating                       9145 non-null   float64
 21  PORPAG                          9189 non-null   float64
 22  usage                           9839 non-null   float64
 23  assistsTurnoverRatio            7786 non-null   float64
 24  offensiveReboundPct             8566 non-null   float64
 25  freeThrowRate                   9222 non-null   float64
 26  effectiveFieldGoalPct           9222 non-null   float64
 27  trueShootingPct                 9299 non-null   float64
 28  fieldGoals/made                 9861 non-null   int64
 29  fieldGoals/attempted            9861 non-null   int64
 30  fieldGoals/pct                  9861 non-null   float64
 31  twoPointFieldGoals/made         9861 non-null   int64
 32  twoPointFieldGoals/attempted    9861 non-null   int64
 33  twoPointFieldGoals/pct          9861 non-null   float64
 34  threePointFieldGoals/made       9861 non-null   int64
 35  threePointFieldGoals/attempted  9861 non-null   int64
 36  threePointFieldGoals/pct        9861 non-null   float64
 37  freeThrows/made                 9861 non-null   int64
 38  freeThrows/attempted            9861 non-null   int64
 39  freeThrows/pct                  9861 non-null   float64
 40  rebounds/offensive              9861 non-null   int64
 41  rebounds/defensive              9861 non-null   int64
 42  rebounds/total                  9861 non-null   int64
 43  winShares/offensive             9146 non-null   float64
 44  winShares/defensive             9786 non-null   float64
 45  winShares/total                 9145 non-null   float64
 46  winShares/totalPer40            9145 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3782
athleteId                            0
athleteSourceId                      0
name                                 0
position                             0
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    672
defensiveRating                     75
netRating                          716
PORPAG                             672
usage                               22
assistsTurnoverRatio              2075
offensiveReboundPct               1295
freeThrowRate                      639
effectiveFieldGoalPct              639
trueShootingPct                    562
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                715
winShares/defensive                 75
winShares/total                    716
winShares/totalPer40               716
dtype: int64
Duplicate rows: 0

Missing data for 2022:

                       Missing Count  Missing Percentage
conference                      3782               38.35
assistsTurnoverRatio            2075               21.04
offensiveReboundPct             1295               13.13
winShares/totalPer40             716                7.26
winShares/total                  716                7.26
netRating                        716                7.26
winShares/offensive              715                7.25
offensiveRating                  672                6.81
PORPAG                           672                6.81
freeThrowRate                    639                6.48
effectiveFieldGoalPct            639                6.48
trueShootingPct                  562                5.70
defensiveRating                   75                0.76
winShares/defensive               75                0.76
usage                             22                0.22

========================================
Player Stats 2023
<class 'pandas.DataFrame'>
RangeIndex: 9752 entries, 0 to 9751
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9752 non-null   int64
 1   seasonLabel                     9752 non-null   int64
 2   teamId                          9752 non-null   int64
 3   team                            9752 non-null   str
 4   conference                      6375 non-null   str
 5   athleteId                       9752 non-null   int64
 6   athleteSourceId                 9752 non-null   int64
 7   name                            9752 non-null   str
 8   position                        9750 non-null   str
 9   games                           9752 non-null   int64
 10  starts                          9752 non-null   int64
 11  minutes                         9752 non-null   int64
 12  points                          9752 non-null   int64
 13  turnovers                       9752 non-null   int64
 14  fouls                           9752 non-null   int64
 15  assists                         9752 non-null   int64
 16  steals                          9752 non-null   int64
 17  blocks                          9752 non-null   int64
 18  offensiveRating                 9024 non-null   float64
 19  defensiveRating                 9591 non-null   float64
 20  netRating                       8925 non-null   float64
 21  PORPAG                          9024 non-null   float64
 22  usage                           9717 non-null   float64
 23  assistsTurnoverRatio            7848 non-null   float64
 24  offensiveReboundPct             8431 non-null   float64
 25  freeThrowRate                   9058 non-null   float64
 26  effectiveFieldGoalPct           9058 non-null   float64
 27  trueShootingPct                 9138 non-null   float64
 28  fieldGoals/made                 9752 non-null   int64
 29  fieldGoals/attempted            9752 non-null   int64
 30  fieldGoals/pct                  9752 non-null   float64
 31  twoPointFieldGoals/made         9752 non-null   int64
 32  twoPointFieldGoals/attempted    9752 non-null   int64
 33  twoPointFieldGoals/pct          9752 non-null   float64
 34  threePointFieldGoals/made       9752 non-null   int64
 35  threePointFieldGoals/attempted  9752 non-null   int64
 36  threePointFieldGoals/pct        9752 non-null   float64
 37  freeThrows/made                 9752 non-null   int64
 38  freeThrows/attempted            9752 non-null   int64
 39  freeThrows/pct                  9752 non-null   float64
 40  rebounds/offensive              9752 non-null   int64
 41  rebounds/defensive              9752 non-null   int64
 42  rebounds/total                  9752 non-null   int64
 43  winShares/offensive             8925 non-null   float64
 44  winShares/defensive             9591 non-null   float64
 45  winShares/total                 8925 non-null   float64
 46  winShares/totalPer40            8925 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3377
athleteId                            0
athleteSourceId                      0
name                                 0
position                             2
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    728
defensiveRating                    161
netRating                          827
PORPAG                             728
usage                               35
assistsTurnoverRatio              1904
offensiveReboundPct               1321
freeThrowRate                      694
effectiveFieldGoalPct              694
trueShootingPct                    614
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                827
winShares/defensive                161
winShares/total                    827
winShares/totalPer40               827
dtype: int64
Duplicate rows: 0

Missing data for 2023:

                       Missing Count  Missing Percentage
conference                      3377               34.63
assistsTurnoverRatio            1904               19.52
offensiveReboundPct             1321               13.55
netRating                        827                8.48
winShares/offensive              827                8.48
winShares/total                  827                8.48
winShares/totalPer40             827                8.48
offensiveRating                  728                7.47
PORPAG                           728                7.47
freeThrowRate                    694                7.12
effectiveFieldGoalPct            694                7.12
trueShootingPct                  614                6.30
defensiveRating                  161                1.65
winShares/defensive              161                1.65
usage                             35                0.36
position                           2                0.02

========================================
Player Stats 2024
<class 'pandas.DataFrame'>
RangeIndex: 9861 entries, 0 to 9860
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9861 non-null   int64
 1   seasonLabel                     9861 non-null   int64
 2   teamId                          9861 non-null   int64
 3   team                            9861 non-null   str
 4   conference                      6079 non-null   str
 5   athleteId                       9861 non-null   int64
 6   athleteSourceId                 9861 non-null   int64
 7   name                            9861 non-null   str
 8   position                        9861 non-null   str
 9   games                           9861 non-null   int64
 10  starts                          9861 non-null   int64
 11  minutes                         9861 non-null   int64
 12  points                          9861 non-null   int64
 13  turnovers                       9861 non-null   int64
 14  fouls                           9861 non-null   int64
 15  assists                         9861 non-null   int64
 16  steals                          9861 non-null   int64
 17  blocks                          9861 non-null   int64
 18  offensiveRating                 9189 non-null   float64
 19  defensiveRating                 9786 non-null   float64
 20  netRating                       9145 non-null   float64
 21  PORPAG                          9189 non-null   float64
 22  usage                           9839 non-null   float64
 23  assistsTurnoverRatio            7786 non-null   float64
 24  offensiveReboundPct             8566 non-null   float64
 25  freeThrowRate                   9222 non-null   float64
 26  effectiveFieldGoalPct           9222 non-null   float64
 27  trueShootingPct                 9299 non-null   float64
 28  fieldGoals/made                 9861 non-null   int64
 29  fieldGoals/attempted            9861 non-null   int64
 30  fieldGoals/pct                  9861 non-null   float64
 31  twoPointFieldGoals/made         9861 non-null   int64
 32  twoPointFieldGoals/attempted    9861 non-null   int64
 33  twoPointFieldGoals/pct          9861 non-null   float64
 34  threePointFieldGoals/made       9861 non-null   int64
 35  threePointFieldGoals/attempted  9861 non-null   int64
 36  threePointFieldGoals/pct        9861 non-null   float64
 37  freeThrows/made                 9861 non-null   int64
 38  freeThrows/attempted            9861 non-null   int64
 39  freeThrows/pct                  9861 non-null   float64
 40  rebounds/offensive              9861 non-null   int64
 41  rebounds/defensive              9861 non-null   int64
 42  rebounds/total                  9861 non-null   int64
 43  winShares/offensive             9146 non-null   float64
 44  winShares/defensive             9786 non-null   float64
 45  winShares/total                 9145 non-null   float64
 46  winShares/totalPer40            9145 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3782
athleteId                            0
athleteSourceId                      0
name                                 0
position                             0
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    672
defensiveRating                     75
netRating                          716
PORPAG                             672
usage                               22
assistsTurnoverRatio              2075
offensiveReboundPct               1295
freeThrowRate                      639
effectiveFieldGoalPct              639
trueShootingPct                    562
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                715
winShares/defensive                 75
winShares/total                    716
winShares/totalPer40               716
dtype: int64
Duplicate rows: 0

Missing data for 2024:

                       Missing Count  Missing Percentage
conference                      3782               38.35
assistsTurnoverRatio            2075               21.04
offensiveReboundPct             1295               13.13
winShares/totalPer40             716                7.26
winShares/total                  716                7.26
netRating                        716                7.26
winShares/offensive              715                7.25
offensiveRating                  672                6.81
PORPAG                           672                6.81
freeThrowRate                    639                6.48
effectiveFieldGoalPct            639                6.48
trueShootingPct                  562                5.70
defensiveRating                   75                0.76
winShares/defensive               75                0.76
usage                             22                0.22

========================================
Player Stats 2025
<class 'pandas.DataFrame'>
RangeIndex: 9808 entries, 0 to 9807
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          9808 non-null   int64
 1   seasonLabel                     9808 non-null   int64
 2   teamId                          9808 non-null   int64
 3   team                            9808 non-null   str
 4   conference                      6280 non-null   str
 5   athleteId                       9808 non-null   int64
 6   athleteSourceId                 9808 non-null   int64
 7   name                            9808 non-null   str
 8   position                        9786 non-null   str
 9   games                           9808 non-null   int64
 10  starts                          9808 non-null   int64
 11  minutes                         9808 non-null   int64
 12  points                          9808 non-null   int64
 13  turnovers                       9808 non-null   int64
 14  fouls                           9808 non-null   int64
 15  assists                         9808 non-null   int64
 16  steals                          9808 non-null   int64
 17  blocks                          9808 non-null   int64
 18  offensiveRating                 9130 non-null   float64
 19  defensiveRating                 9495 non-null   float64
 20  netRating                       8889 non-null   float64
 21  PORPAG                          9130 non-null   float64
 22  usage                           9771 non-null   float64
 23  assistsTurnoverRatio            7785 non-null   float64
 24  offensiveReboundPct             8470 non-null   float64
 25  freeThrowRate                   9156 non-null   float64
 26  effectiveFieldGoalPct           9156 non-null   float64
 27  trueShootingPct                 9260 non-null   float64
 28  fieldGoals/made                 9808 non-null   int64
 29  fieldGoals/attempted            9808 non-null   int64
 30  fieldGoals/pct                  9808 non-null   float64
 31  twoPointFieldGoals/made         9808 non-null   int64
 32  twoPointFieldGoals/attempted    9808 non-null   int64
 33  twoPointFieldGoals/pct          9808 non-null   float64
 34  threePointFieldGoals/made       9808 non-null   int64
 35  threePointFieldGoals/attempted  9808 non-null   int64
 36  threePointFieldGoals/pct        9808 non-null   float64
 37  freeThrows/made                 9808 non-null   int64
 38  freeThrows/attempted            9808 non-null   int64
 39  freeThrows/pct                  9808 non-null   float64
 40  rebounds/offensive              9808 non-null   int64
 41  rebounds/defensive              9808 non-null   int64
 42  rebounds/total                  9808 non-null   int64
 43  winShares/offensive             8889 non-null   float64
 44  winShares/defensive             9495 non-null   float64
 45  winShares/total                 8889 non-null   float64
 46  winShares/totalPer40            8889 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.5 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3528
athleteId                            0
athleteSourceId                      0
name                                 0
position                            22
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    678
defensiveRating                    313
netRating                          919
PORPAG                             678
usage                               37
assistsTurnoverRatio              2023
offensiveReboundPct               1338
freeThrowRate                      652
effectiveFieldGoalPct              652
trueShootingPct                    548
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                919
winShares/defensive                313
winShares/total                    919
winShares/totalPer40               919
dtype: int64
Duplicate rows: 0

Missing data for 2025:

                       Missing Count  Missing Percentage
conference                      3528               35.97
assistsTurnoverRatio            2023               20.63
offensiveReboundPct             1338               13.64
netRating                        919                9.37
winShares/offensive              919                9.37
winShares/total                  919                9.37
winShares/totalPer40             919                9.37
offensiveRating                  678                6.91
PORPAG                           678                6.91
freeThrowRate                    652                6.65
effectiveFieldGoalPct            652                6.65
trueShootingPct                  548                5.59
defensiveRating                  313                3.19
winShares/defensive              313                3.19
usage                             37                0.38
position                          22                0.22

========================================
Player Stats 2026
<class 'pandas.DataFrame'>
RangeIndex: 10030 entries, 0 to 10029
Data columns (total 47 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   season                          10030 non-null  int64
 1   seasonLabel                     10030 non-null  int64
 2   teamId                          10030 non-null  int64
 3   team                            10030 non-null  str
 4   conference                      6213 non-null   str
 5   athleteId                       10030 non-null  int64
 6   athleteSourceId                 10030 non-null  int64
 7   name                            10030 non-null  str
 8   position                        10029 non-null  str
 9   games                           10030 non-null  int64
 10  starts                          10030 non-null  int64
 11  minutes                         10030 non-null  int64
 12  points                          10030 non-null  int64
 13  turnovers                       10030 non-null  int64
 14  fouls                           10030 non-null  int64
 15  assists                         10030 non-null  int64
 16  steals                          10030 non-null  int64
 17  blocks                          10030 non-null  int64
 18  offensiveRating                 9383 non-null   float64
 19  defensiveRating                 9922 non-null   float64
 20  netRating                       9311 non-null   float64
 21  PORPAG                          9382 non-null   float64
 22  usage                           9999 non-null   float64
 23  assistsTurnoverRatio            7962 non-null   float64
 24  offensiveReboundPct             8627 non-null   float64
 25  freeThrowRate                   9385 non-null   float64
 26  effectiveFieldGoalPct           9385 non-null   float64
 27  trueShootingPct                 9455 non-null   float64
 28  fieldGoals/made                 10030 non-null  int64
 29  fieldGoals/attempted            10030 non-null  int64
 30  fieldGoals/pct                  10030 non-null  float64
 31  twoPointFieldGoals/made         10030 non-null  int64
 32  twoPointFieldGoals/attempted    10030 non-null  int64
 33  twoPointFieldGoals/pct          10030 non-null  float64
 34  threePointFieldGoals/made       10030 non-null  int64
 35  threePointFieldGoals/attempted  10030 non-null  int64
 36  threePointFieldGoals/pct        10030 non-null  float64
 37  freeThrows/made                 10030 non-null  int64
 38  freeThrows/attempted            10030 non-null  int64
 39  freeThrows/pct                  10030 non-null  float64
 40  rebounds/offensive              10030 non-null  int64
 41  rebounds/defensive              10030 non-null  int64
 42  rebounds/total                  10030 non-null  int64
 43  winShares/offensive             9312 non-null   float64
 44  winShares/defensive             9922 non-null   float64
 45  winShares/total                 9311 non-null   float64
 46  winShares/totalPer40            9311 non-null   float64
dtypes: float64(18), int64(25), str(4)
memory usage: 3.6 MB
Missing values:
 season                               0
seasonLabel                          0
teamId                               0
team                                 0
conference                        3817
athleteId                            0
athleteSourceId                      0
name                                 0
position                             1
games                                0
starts                               0
minutes                              0
points                               0
turnovers                            0
fouls                                0
assists                              0
steals                               0
blocks                               0
offensiveRating                    647
defensiveRating                    108
netRating                          719
PORPAG                             648
usage                               31
assistsTurnoverRatio              2068
offensiveReboundPct               1403
freeThrowRate                      645
effectiveFieldGoalPct              645
trueShootingPct                    575
fieldGoals/made                      0
fieldGoals/attempted                 0
fieldGoals/pct                       0
twoPointFieldGoals/made              0
twoPointFieldGoals/attempted         0
twoPointFieldGoals/pct               0
threePointFieldGoals/made            0
threePointFieldGoals/attempted       0
threePointFieldGoals/pct             0
freeThrows/made                      0
freeThrows/attempted                 0
freeThrows/pct                       0
rebounds/offensive                   0
rebounds/defensive                   0
rebounds/total                       0
winShares/offensive                718
winShares/defensive                108
winShares/total                    719
winShares/totalPer40               719
dtype: int64
Duplicate rows: 0

Missing data for 2026:

                       Missing Count  Missing Percentage
conference                      3817               38.06
assistsTurnoverRatio            2068               20.62
offensiveReboundPct             1403               13.99
netRating                        719                7.17
winShares/totalPer40             719                7.17
winShares/total                  719                7.17
winShares/offensive              718                7.16
PORPAG                           648                6.46
offensiveRating                  647                6.45
freeThrowRate                    645                6.43
effectiveFieldGoalPct            645                6.43
trueShootingPct                  575                5.73
defensiveRating                  108                1.08
winShares/defensive              108                1.08
usage                             31                0.31
position                           1                0.01

### Confirm how seasons and IDs line up across datasets ###

**Clean season**

In [36]:
import numpy as np
import matplotlib.pyplot as plt

all_stats = pd.concat(datasets.values(), ignore_index=True) # Combine all datasets to explore values
print(all_stats.groupby("season")[["season", "seasonLabel"]].first()) # Group by season

        season  seasonLabel
season
2020      2020     20192020
2023      2023     20222023
2024      2024     20232024
2025      2025     20242025
2026      2026     20252026

We will define the season as the year when that season ends. For example, the 2020 season was played over 2019 and 2020. I can now delete the `seasonLabel` column in all the datasets.

In [37]:
for year, df in datasets.items():
    datasets[year] = df.drop(columns=["seasonLabel"]) # Drop seasonLabel for each dataset

print(f"Season Missing values: {all_stats["season"].isna().sum()}") # Determing missing values
datasets['2020'].head() # Check head

Season Missing values: 0

,season,teamId,team,conference,athleteId,athleteSourceId,name,position,games,starts,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,1,Abilene Christian,Southland,16870,4433077,Airion Simmons,F,31,0,...,23,39,59.0,40,87,127,0.5,0.9,1.4,0.129
1,2020,1,Abilene Christian,Southland,21203,4397957,Damien Daniels,G,31,15,...,32,43,74.4,16,58,74,0.5,0.8,1.3,0.083
2,2020,1,Abilene Christian,Southland,21204,4278255,Tobias Cameron,G,25,0,...,10,11,90.9,11,17,28,0.3,0.2,0.5,0.143
3,2020,1,Abilene Christian,Southland,21205,4397958,Joe Pleasant,F,29,29,...,68,97,70.1,49,73,122,1.3,0.7,2.0,0.112
4,2020,1,Abilene Christian,Southland,27157,4593748,Mahki Morris,G,17,1,...,14,17,82.4,14,13,27,0.0,0.4,0.4,0.084

The `season` column is good to go.

**Clean athleteID**

In [38]:
print(all_stats[["athleteId", "athleteSourceId"]].nunique()) # How many unique values are in athleteId vs athleteSourceId

print(f"\nathleteSourceIds for each athleteId:\n{all_stats.groupby('athleteId')['athleteSourceId'].nunique().value_counts()}") # Check how many sourceIds there are for each athleteID
print(all_stats[["athleteId", "athleteSourceId"]].head())

athleteId          32077
athleteSourceId    32077
dtype: int64

athleteSourceIds for each athleteId:
athleteSourceId
1    32077
Name: count, dtype: int64
   athleteId  athleteSourceId
0      16870          4433077
1      21203          4397957
2      21204          4278255
3      21205          4397958
4      27157          4593748

`athleteId` and `athleteSourceId` have different values but map one-to-one, so they carry the same information and each have the same number of unique values. Therefore, I will drop one column and just keep `athleteId`.

In [39]:
for year, df in datasets.items():
    datasets[year] = df.drop(columns=["athleteSourceId"]) # Drop athleteSourceId for each dataset

In [40]:
print(f"athleteId missing values: {all_stats['athleteId'].isna().sum()}")
datasets['2020'].head() # Check head

athleteId missing values: 0

,season,teamId,team,conference,athleteId,name,position,games,starts,minutes,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,1,Abilene Christian,Southland,16870,Airion Simmons,F,31,0,434,...,23,39,59.0,40,87,127,0.5,0.9,1.4,0.129
1,2020,1,Abilene Christian,Southland,21203,Damien Daniels,G,31,15,630,...,32,43,74.4,16,58,74,0.5,0.8,1.3,0.083
2,2020,1,Abilene Christian,Southland,21204,Tobias Cameron,G,25,0,140,...,10,11,90.9,11,17,28,0.3,0.2,0.5,0.143
3,2020,1,Abilene Christian,Southland,21205,Joe Pleasant,F,29,29,713,...,68,97,70.1,49,73,122,1.3,0.7,2.0,0.112
4,2020,1,Abilene Christian,Southland,27157,Mahki Morris,G,17,1,191,...,14,17,82.4,14,13,27,0.0,0.4,0.4,0.084

In [41]:
rows_per_athlete = all_stats.groupby(["season", "athleteId"]).size() # Group by season and athleteId to see how many ahtletes are featured multiple times in one season
print(f"Rows per athlete within a season:\n{rows_per_athlete.value_counts()}")

print(f"\nNumber of duplicate athletes by season:\n{(rows_per_athlete > 1).groupby("season").sum()}")

Rows per athlete within a season:
1    38305
3     9861
2       60
Name: count, dtype: int64

Number of duplicate athletes by season:
season
2020      38
2023       0
2024    9861
2025      20
2026       2
dtype: int64

I looked at how many athletes are featured multiple times in just one season, and saw that there are 70 players who appear twice. This means that only 70 out of 64,475 athlete-seasons (0.1%) have a repeat. I am going to see what those 70 cases are. No players appear three times.

In [42]:
duplicates = all_stats[all_stats.duplicated(subset=["season", "athleteId"], keep=False)] # Find all the duplicated players
print(duplicates.sort_values(["athleteId", "season"])[["athleteId", "name", "season", "team", "games", "points"]].to_string(index=False)) # Inspect the duplicated players

 athleteId                         name  season                                     team  games  points
         1               Chaney Johnson    2024                                   Auburn     35     166
         1               Chaney Johnson    2024                                   Auburn     35     166
         1               Chaney Johnson    2024                                   Auburn     35     166
         2               Dylan Cardwell    2024                                   Auburn     35     185
         2               Dylan Cardwell    2024                                   Auburn     35     185
         2               Dylan Cardwell    2024                                   Auburn     35     185
         3            Chad Baker-Mazara    2024                                   Auburn     35     350
         3            Chad Baker-Mazara    2024                                   Auburn     35     350
         3            Chad Baker-Mazara    2024                                   Auburn     35     350
         4                 Denver Jones    2024                                   Auburn     35     318
         4                 Denver Jones    2024                                   Auburn     35     318
         4                 Denver Jones    2024                                   Auburn     35     318
         5                  Miles Kelly    2024                             Georgia Tech     32     446
         5                  Miles Kelly    2024                             Georgia Tech     32     446
         5                  Miles Kelly    2024                             Georgia Tech     32     446
         6               Ja'Heim Hudson    2024                                      SMU     31     166
         6               Ja'Heim Hudson    2024                                      SMU     31     166
         6               Ja'Heim Hudson    2024                                      SMU     31     166
         8                  Chris Moore    2024                                   Auburn     34      85
         8                  Chris Moore    2024                                   Auburn     34      85
         8                  Chris Moore    2024                                   Auburn     34      85
        10                Addarin Scott    2024                                   Auburn     15       6
        10                Addarin Scott    2024                                   Auburn     15       6
        10                Addarin Scott    2024                                   Auburn     15       6
        11                 Johni Broome    2024                                   Auburn     35     576
        11                 Johni Broome    2024                                   Auburn     35     576
        11                 Johni Broome    2024                                   Auburn     35     576
        15              Blake Muschalek    2024                                   Auburn     15       8
        15              Blake Muschalek    2024                                   Auburn     15       8
        15              Blake Muschalek    2024                                   Auburn     15       8
        17            Presley Patterson    2024                                   Auburn      3       0
        17            Presley Patterson    2024                                   Auburn      3       0
        17            Presley Patterson    2024                                   Auburn      3       0
        18                    JP Pegues    2024                                   Furman     30     553
        18                    JP Pegues    2024                                   Furman     30     553
        18                    JP Pegues    2024                                   Furman     30     553
        19                   RJ Godfrey    2024                                  Clemson     36     219
        19                   RJ Godfrey    2024                                  Clemson     36     219
        19                   RJ Godfrey    2024                                  Clemson     36     219
        21                    Blue Cain    2024                                  Georgia     37     274
        21                    Blue Cain    2024                                  Georgia     37     274
        21                    Blue Cain    2024                                  Georgia     37     274
        22             Silas Demary Jr.    2024                                  Georgia     37     359
        22             Silas Demary Jr.    2024                                  Georgia     37     359
        22             Silas Demary Jr.    2024                                  Georgia     37     359
        23               Tyrin Lawrence    2024                               Vanderbilt     28     386
        23               Tyrin Lawrence    2024                               Vanderbilt     28     386
        23               Tyrin Lawrence    2024                               Vanderbilt     28     386
        26         De'Shayne Montgomery    2024                         Mount St. Mary's     32     423
        26         De'Shayne Montgomery    2024                         Mount St. Mary's     32     423
        26         De'Shayne Montgomery    2024                         Mount St. Mary's     32     423
        27                Dakota Leffew    2024                         Mount St. Mary's     30     529
        27                Dakota Leffew    2024                         Mount St. Mary's     30     529
        27                Dakota Leffew    2024                         Mount St. Mary's     30     529
        28                 Jaden Newell    2024                                  Georgia      3       2
        28                 Jaden Newell    2024                                  Georgia      3       2
        28                 Jaden Newell    2024                                  Georgia      3       2
        29                  Dylan James    2024                                  Georgia     22      88
        29                  Dylan James    2024                                  Georgia     22      88
        29                  Dylan James    2024                                  Georgia     22      88
        33              Brandon Klatsky    2024                                  Georgia      3       0
        33              Brandon Klatsky    2024                                  Georgia      3       0
        33              Brandon Klatsky    2024                                  Georgia      3       0
        34            Dominick Campbell    2024                                   Howard     26     204
        34            Dominick Campbell    2024                                   Howard     26     204
        34            Dominick Campbell    2024                                   Howard     26     204
        36                 Bryce Harris    2024                                   Howard     35     580
        36                 Bryce Harris    2024                                   Howard     35     580
        36                 Bryce Harris    2024                                   Howard     35     580
        37                   Anwar Gill    2024                                 La Salle     29     271
        37                   Anwar Gill    2024                                 La Salle     29     271
        37                   Anwar Gill    2024                                 La Salle     29     271
        38               Marcus Dockery    2024                                   Howard     35     474
        38               Marcus Dockery    2024                                   Howard     35     474
        38               Marcus Dockery    2024                                   Howard     35     474
        39                Ayodele Taiwo    2024                                   Howard      8      11
        39                Ayodele Taiwo    2024                                   Howard      8      11
        39                Ayodele Taiwo    2024                                   Howard      8      11
        40                Miles Stewart    2024                                   Howard     24      19
        40                Miles Stewart    2024                                   Howard     24      19
        40                Miles Stewart    2024                                   Howard     24      19
        42                   Ose Okojie    2024                                   Howard     19      76
        42                   Ose Okojie    2024                                   Howard     19      76
        42                   Ose Okojie    2024                                   Howard     19      76
        43                Joshua Strong    2024                                   Howard     31     109
        43                Joshua Strong    2024                                   Howard     31     109
        43                Joshua Strong    2024                                   Howard     31     109
        44                Jaren Johnson    2024                                Dartmouth     26     191
        44                Jaren Johnson    2024                                Dartmouth     26     191
        44                Jaren Johnson    2024                                Dartmouth     26     191
        45                  Mounir Hima    2024                                 Syracuse     13       4
        45                  Mounir Hima    2024                                 Syracuse     13       4
        45                  Mounir Hima    2024                                 Syracuse     13       4
        47                 KJ Adams Jr.    2024                                   Kansas     34     428
        47                 KJ Adams Jr.    2024                                   Kansas     34     428
        47                 KJ Adams Jr.    2024                                   Kansas     34     428
        48             Hunter Dickinson    2024                                   Kansas     33     591
        48             Hunter Dickinson    2024                                   Kansas     33     591
        48             Hunter Dickinson    2024                                   Kansas     33     591
        49                   David Coit    2024                        Northern Illinois     29     602
        49                   David Coit    2024                        Northern Illinois     29     602
        49                   David Coit    2024                        Northern Illinois     29     602
        50                Rylan Griffen    2024                                  Alabama     36     402
        50                Rylan Griffen    2024                                  Alabama     36     402
        50                Rylan Griffen    2024                                  Alabama     36     402
        51            Dajuan Harris Jr.    2024                                   Kansas     34     289
        51            Dajuan Harris Jr.    2024                                   Kansas     34     289
        51            Dajuan Harris Jr.    2024                                   Kansas     34     289
        56              Patrick Cassidy    2024                                   Kansas      6       5
        56              Patrick Cassidy    2024                                   Kansas      6       5
        56              Patrick Cassidy    2024                                   Kansas      6       5
        57                 Wilder Evers    2024                                   Kansas      8       6
        57                 Wilder Evers    2024                                   Kansas      8       6
        57                 Wilder Evers    2024                                   Kansas      8       6
        58                     AJ Storr    2024                                Wisconsin     36     605
        58                     AJ Storr    2024                                Wisconsin     36     605
        58                     AJ Storr    2024                                Wisconsin     36     605
        60                    Zeke Mayo    2024                       South Dakota State     35     658
        60                    Zeke Mayo    2024                       South Dakota State     35     658
        60                    Zeke Mayo    2024                       South Dakota State     35     658
        61               Dillon Wilhite    2024                                   Kansas      9       3
        61               Dillon Wilhite    2024                                   Kansas      9       3
        61               Dillon Wilhite    2024                                   Kansas      9       3
        62              Jamari McDowell    2024                                   Kansas     31      57
        62              Jamari McDowell    2024                                   Kansas     31      57
        62              Jamari McDowell    2024                                   Kansas     31      57
        63              Elmarko Jackson    2024                                   Kansas     34     146
        63              Elmarko Jackson    2024                                   Kansas     34     146
        63              Elmarko Jackson    2024                                   Kansas     34     146
        64                  Noah Shelby    2024                                     Rice     30     118
        64                  Noah Shelby    2024                                     Rice     30     118
        64                  Noah Shelby    2024                                     Rice     30     118
        65                Shakeel Moore    2024                        Mississippi State     33     261
        65                Shakeel Moore    2024                        Mississippi State     33     261
        65                Shakeel Moore    2024                        Mississippi State     33     261
        66                Toyaz Solomon    2024                            UNC Asheville     33     199
        66                Toyaz Solomon    2024                            UNC Asheville     33     199
        66                Toyaz Solomon    2024                            UNC Asheville     33     199
        67               Greg Gantt Jr.    2024                            UNC Asheville     17      30
        67               Greg Gantt Jr.    2024                            UNC Asheville     17      30
        67               Greg Gantt Jr.    2024                            UNC Asheville     17      30
        68                 Jordan Marsh    2024                                App State     32     199
        68                 Jordan Marsh    2024                                App State     32     199
        68                 Jordan Marsh    2024                                App State     32     199
        69                  Aidan Rubio    2024                         Central Michigan     27     184
        69                  Aidan Rubio    2024                         Central Michigan     27     184
        69                  Aidan Rubio    2024                         Central Michigan     27     184
        70                Fletcher Abee    2024                            UNC Asheville     34     361
        70                Fletcher Abee    2024                            UNC Asheville     34     361
        70                Fletcher Abee    2024                            UNC Asheville     34     361
        71               Sage Tolentino    2024                               Cincinnati      5       0
        71               Sage Tolentino    2024                               Cincinnati      5       0
        71               Sage Tolentino    2024                               Cincinnati      5       0
        74                  Corey Jones    2024                            UNC Asheville      4       7
        74                  Corey Jones    2024                            UNC Asheville      4       7
        74                  Corey Jones    2024                            UNC Asheville      4       7
        76                Connor Dubsky    2024                             Rhode Island     14      30
        76                Connor Dubsky    2024                             Rhode Island     14      30
        76                Connor Dubsky    2024                             Rhode Island     14      30
        77                   Josh Banks    2024                            UNC Asheville     34     436
        77                   Josh Banks    2024                            UNC Asheville     34     436
        77                   Josh Banks    2024                            UNC Asheville     34     436
        78                  Jemal Davis    2024                         Central Michigan     31     171
        78                  Jemal Davis    2024                         Central Michigan     31     171
        78                  Jemal Davis    2024                         Central Michigan     31     171
        80              Rasheed Baldwin    2024                            UNC Asheville      5       6
        80              Rasheed Baldwin    2024                            UNC Asheville      5       6
        80              Rasheed Baldwin    2024                            UNC Asheville      5       6
        81                Justin Wright    2024                         Loyola Marymount     29     322
        81                Justin Wright    2024                         Loyola Marymount     29     322
        81                Justin Wright    2024                         Loyola Marymount     29     322
        83              Jarin Stevenson    2024                                  Alabama     37     195
        83              Jarin Stevenson    2024                                  Alabama     37     195
        83              Jarin Stevenson    2024                                  Alabama     37     195
        84             Clifford Omoruyi    2024                                  Rutgers     32     333
        84             Clifford Omoruyi    2024                                  Rutgers     32     333
        84             Clifford Omoruyi    2024                                  Rutgers     32     333
        86                   Mark Sears    2024                                  Alabama     37     797
        86                   Mark Sears    2024                                  Alabama     37     797
        86                   Mark Sears    2024                                  Alabama     37     797
        87              Max Scharnowski    2024                                  Alabama     12       7
        87              Max Scharnowski    2024                                  Alabama     12       7
        87              Max Scharnowski    2024                                  Alabama     12       7
        88            Mouhamed Dioubate    2024                                  Alabama     33      97
        88            Mouhamed Dioubate    2024                                  Alabama     33      97
        88            Mouhamed Dioubate    2024                                  Alabama     33      97
        90                 Grant Nelson    2024                                  Alabama     37     440
        90                 Grant Nelson    2024                                  Alabama     37     440
        90                 Grant Nelson    2024                                  Alabama     37     440
        91           Latrell Wrightsell    2024                                  Alabama     31     277
        91           Latrell Wrightsell    2024                                  Alabama     31     277

The athletes that are duplicated within a season are shown on different teams in the same season. I did some research, using Brendan Terry as an example, and found that the Southeast Missouri State players who played in their game against UNC Asheville each have a separate row for that game, where they are mislabeled as UNC Asheville players. The points in those rows match the points the players scored in that game's box score.

The only exception is A.J. Lawson. He is the only athlete where one of his two rows isn't a single game. After researching, I found out this is two different A.J. Lawsons with the same `athleteId` (31449). One played for South Carolina, and the other played for McNeese. I will separate these players and give one of them a different `athleteID`.

After this, for each duplicated athlete, I will keep the row with the most games, since that is the team they actually played for.

In [43]:
# athleteId 31449 is shared by two different players named A.J. Lawson (McNeese and South Carolina).
# Give the South Carolina player his own ID so the two are no longer mixed up.
new_id = max(df["athleteId"].max() for df in datasets.values()) + 1 # Determine the max athleteId and add one

for year, df in datasets.items(): # Give the SC player a new athleteId
    is_sc_lawson = (df["athleteId"] == 31449) & (df["team"] == "South Carolina")
    df.loc[is_sc_lawson, "athleteId"] = new_id

In [44]:
for year, df in datasets.items():
    # For athletes with two team rows in one season, keep the row with the most games (or minutes if games are tied)
    df = df.sort_values(["games", "minutes"], ascending=False)
    df = df.drop_duplicates(subset=["season", "athleteId"], keep="first")
    datasets[year] = df.sort_values("athleteId").reset_index(drop=True)

all_stats = pd.concat(datasets.values(), ignore_index=True) # Rebuild combined table from cleaned datasets

print(f"Duplicate athlete-seasons left: {all_stats.duplicated(subset=['season', 'athleteId']).sum()}") # Check how many duplicates are left
print(f"Rows: {len(all_stats)}\n")
print("A.J. Lawson after the split:")
print(all_stats[all_stats["name"] == "A.J. Lawson"][["athleteId", "season", "team", "games"]]
      .sort_values(["athleteId", "season"]).to_string(index=False))
datasets['2020'].head() # Check head

Duplicate athlete-seasons left: 19722
Rows: 67949

A.J. Lawson after the split:
 athleteId  season           team  games
     31449    2020        McNeese     32
    223021    2020 South Carolina     31

,season,teamId,team,conference,athleteId,name,position,games,starts,minutes,...,freeThrows/made,freeThrows/attempted,freeThrows/pct,rebounds/offensive,rebounds/defensive,rebounds/total,winShares/offensive,winShares/defensive,winShares/total,winShares/totalPer40
0,2020,58,Columbia,Ivy,41,Cameron Shockley-Okeke,F,13,0,143,...,3,4,75.0,5,19,24,-0.4,0.3,-0.1,-0.028
1,2020,235,Providence,Big East,67,Greg Gantt Jr.,F,27,5,338,...,13,19,68.4,26,36,62,0.0,0.7,0.7,0.083
2,2020,299,The Citadel,SoCon,70,Fletcher Abee,G,30,30,969,...,45,53,84.9,10,47,57,1.8,0.4,2.2,0.091
3,2020,145,Long Beach State,Big West,96,Romelle Mansel,F,32,23,631,...,32,65,49.2,29,84,113,-0.7,0.5,-0.2,-0.013
4,2020,148,Louisiana,Sun Belt,122,Mylik Wilson,G,29,24,991,...,48,68,70.6,34,132,166,0.8,1.5,2.3,0.093

The duplicate athletes were handled correctly.

In [45]:
print(f"athleteIds with more than one name: {(all_stats.groupby('athleteId')['name'].nunique() > 1).sum()}") # Check names and athleteId

year_shifted_forward = all_stats.copy() # Copy the table
year_shifted_forward["season"] = year_shifted_forward["season"] + 1 # Add one to each season to check how athleteId's move between the prior season 

both_years = all_stats.merge(year_shifted_forward, on=["athleteId", "season"], suffixes=("_this_year", "_last_year")) # Inner join each player's rows with his row from the year before

changed_team = both_years["teamId_this_year"] != both_years["teamId_last_year"] # Check to see if teamId is different from year to year

print(f"Players found in two consecutive seasons: {len(both_years)}")
print(f"Players found in two consecutive seasons who changed teams: {changed_team.sum()}")

athleteIds with more than one name: 0
Players found in two consecutive seasons: 31611
Players found in two consecutive seasons who changed teams: 8498

No athleteIds have more than one name, and the same `athleteId` shows up across consecutive seasons, even when a player changes teams, which is great news. There are 6,194 cases of a player appearing on a different team than the season before. This does include non-D1 schools, so this number will shrink once we filter to D1. The `athleteID` column is good to go.

In [46]:
#preparing/cleaning
all_stats = pd.concat(
    [
        df.assign(dataset_year=int(year))
        for year, df in datasets.items()
    ],
    ignore_index=True
)

missing_conf = all_stats[all_stats["conference"].isna()]

missing_schools = (
    missing_conf.groupby(["dataset_year", "team"])
    .size()
    .reset_index(name="players_missing_conference")
    .sort_values(
        ["dataset_year", "players_missing_conference"],
        ascending=[True, False]
    )
)

school_conferences = (
    all_stats[all_stats["conference"].notna()]
    .groupby("team")["conference"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index(name="conferences_found")
)

missing_schools_check = missing_schools.merge(
    school_conferences,
    on="team",
    how="left"
)

display(missing_schools_check)

,dataset_year,team,players_missing_conference,conferences_found
0,2020,Lindenwood,24,[OVC]
1,2020,Bethesda University,22,NaN
2,2020,Westcliff,21,NaN
3,2020,Trinity Baptist,20,NaN
4,2020,Northland,19,NaN
...,...,...,...,...
1781,2026,Miami (OH)-Middletown,8,NaN
1782,2026,Rust,8,NaN
1783,2026,Maine-Fort Kent,7,NaN
1784,2026,Williams Baptist,7,NaN
1785,2026,Regis (CO),6,NaN

**Mapping schools missing conferences**

In [47]:

import requests
import pandas as pd

base_url = "https://web3.ncaa.org/directory/api/directory/memberList"

def get_schools(division):
    params = {
        "type": 12,
        "division": division,
        "sportCode": "MBB"
    }

    response = requests.get(base_url, params=params, timeout=30)
    response.raise_for_status()

    df = pd.DataFrame(response.json())

    df = df[["nameOfficial", "division", "conferenceName"]].copy()
    df.columns = ["school_name", "division_number", "conference"]

    df["division_label"] = df["division_number"].map({
        2: "D2",
        3: "D3"
    })

    expected_number = {"II": 2, "III": 3}[division]
    df = df[df["division_number"] == expected_number].copy()

    return df[["school_name", "division_label", "conference"]]

d2_df = get_schools("II")
d3_df = get_schools("III")

schools_df = pd.concat([d2_df, d3_df], ignore_index=True)

print(schools_df.head(10))
print("\nSchools by division:")
print(schools_df.groupby("division_label").size())

assert set(schools_df["division_label"].dropna()) == {"D2", "D3"}

schools_df.to_csv("data/ncaa_d2_d3_mens_basketball.csv", index=False)
print("\nSaved NCAA Division II and III school reference.")

                            school_name division_label  \
0                Adams State University             D2
1                    Adelphi University             D2
2   University of Alabama in Huntsville             D2
3        University of Alaska Anchorage             D2
4        University of Alaska Fairbanks             D2
5     Albany State University (Georgia)             D2
6                      Allen University             D2
7        American International College             D2
8  Anderson University (South Carolina)             D2
9               Angelo State University             D2

                            conference
0   Rocky Mountain Athletic Conference
1              Northeast 10 Conference
2                Gulf South Conference
3  Great Northwest Athletic Conference
4  Great Northwest Athletic Conference
5        Southern Intercol. Ath. Conf.
6        Southern Intercol. Ath. Conf.
7              Northeast 10 Conference
8            South Atlantic Conference
9                 Lone Star Conference

Schools by division:
division_label
D2    298
D3    406
dtype: int64

Saved NCAA Division II and III school reference.

NCAA missing schools

In [48]:
import pandas as pd
from pathlib import Path

ncaa = pd.read_csv(DATA_DIR / "ncaa_d2_d3_mens_basketball.csv")

def normalize(name):
    return (str(name).lower().strip().replace(".", "").replace(",", "").replace("(", "").replace(")", "").replace("-", " ").split())

def school_key(name):
    return " ".join(normalize(name))

ncaa["school_key"] = ncaa["school_name"].fillna("").apply(school_key)
division_map = ncaa.set_index("school_key")["division_label"].to_dict()

file_2020 = DATA_DIR / "player_stats_2020.csv"
df_2020 = pd.read_csv(file_2020)

missing_2020 = (df_2020["conference"].isna() | df_2020["conference"].astype(str).str.strip().eq(""))

file_2021 = DATA_DIR / "player_stats_2021.csv"
df_2021 = pd.read_csv(file_2021)

missing_2021 = (df_2021["conference"].isna() | df_2021["conference"].astype(str).str.strip().eq(""))

file_2022 = DATA_DIR / "player_stats_2022.csv"
df_2022 = pd.read_csv(file_2022)

missing_2022 = (df_2022["conference"].isna() | df_2022["conference"].astype(str).str.strip().eq(""))

file_2023 = DATA_DIR / "player_stats_2023.csv"
df_2023 = pd.read_csv(file_2023)

missing_2023 = (df_2023["conference"].isna() | df_2023["conference"].astype(str).str.strip().eq(""))

file_2024 = DATA_DIR / "player_stats_2024.csv"
df_2024 = pd.read_csv(file_2024)

missing_2024 = (df_2024["conference"].isna() | df_2024["conference"].astype(str).str.strip().eq(""))

file_2025 = DATA_DIR / "player_stats_2025.csv"
df_2025 = pd.read_csv(file_2025)

missing_2025 = (df_2025["conference"].isna() | df_2025["conference"].astype(str).str.strip().eq(""))

file_2026 = DATA_DIR / "player_stats_2026.csv"
df_2026 = pd.read_csv(file_2026)

missing_2026 = (df_2026["conference"].isna() | df_2026["conference"].astype(str).str.strip().eq(""))

name_overrides = {
    "Centenary (LA)": "Centenary College (Louisiana)",
    "Erskine": "Erskine College",
    "Washington College (MD)": "Washington College (Maryland)",
    "Georgian Court": "Georgian Court University",
    "Piedmont": "Piedmont University",
    "NC Wesleyan": "North Carolina Wesleyan University",
    "William Peace": "William Peace University",
    "Vermont State - Lyndon": "Vermont State University Lyndon",
    "Newberry": "Newberry College",
    "Pfeiffer": "Pfeiffer University",
    "Western Colorado": "Western Colorado University",
    "Maryville College (TN)": "Maryville College (Tennessee)",
    "Trinity (TX)": "Trinity University (Texas)",
    "Western New Mexico": "Western New Mexico University",
    "Howard Payne": "Howard Payne University",
    "Nebraska Wesleyan": "Nebraska Wesleyan University",
    "Widener": "Widener University",
    "Concordia-Chicago": "Concordia University Chicago",
    "Central State Oklahoma": "University of Central Oklahoma",
    "Nebraska-Kearney": "University of Nebraska at Kearney",
    "Carson-Newman": "Carson-Newman University",
    "Missouri-St. Louis": "University of Missouri-St. Louis",
    "East Central (OK)": "East Central University",
    "Geneva": "Geneva College",
    "Caldwell": "Caldwell University",
    "Maine Maritime": "Maine Maritime Academy",
    "Ohio Northern": "Ohio Northern University",
    "Arkansas Tech": "Arkansas Tech University",
    "Cortland": "State University of New York at Cortland",
    "CS San Bernardino": "California State University, San Bernardino",
    "Southwest Baptist": "Southwest Baptist University",
    "Wisconsin-Lutheran": "Wisconsin Lutheran College",
    "Tampa": "University of Tampa",
    "Gettysburg": "Gettysburg College",
    "Hampden-Sydney": "Hampden-Sydney College",
    "Chicago": "University of Chicago",
    "Arkansas-Monticello": "University of Arkansas, Monticello",
    "New Mexico Highlands": "New Mexico Highlands University",
    "San Francisco State": "San Francisco State University",
    "Davenport": "Davenport University",
    "Colorado Christian": "Colorado Christian University",
    "UT Permian Basin": "The University of Texas Permian Basin",
    "Texas Permian Basin": "The University of Texas Permian Basin",
    "North Greenville": "North Greenville University",
    "Central State (OH)": "Central State University",
    "Stanislaus State": "California State University, Stanislaus",
    "Florida Tech": "Florida Institute of Technology",
    "Rogers State": "Rogers State University",
    "Hawai’i Pacific": "Hawaii Pacific University",
    "Kentucky Wesleyan": "Kentucky Wesleyan College",
    "UVA Wise": "The University of Virginia's College at Wise",
    "Morehouse": "Morehouse College",
    "Malone": "Malone University",
    "Delta State": "Delta State University",
    "Fresno Pacific": "Fresno Pacific University",
    #shut down "Sonoma State": "",
    "Tiffin": "Tiffin University",
    "Chaminade": "Chaminade University",
    "Montevallo": "University of Montevallo",
    "E. New Mexico": "Eastern New Mexico University",
    "Coker": "Coker University",
    "Trevecca Nazarene": "Trevecca Nazarene University",
    "Illinois-Springfield": "University of Illinois Springfield",
    "Shorter": "Shorter University",
    "Missouri S&T": "Missouri University of Science and Technology",
    "St. Mary's (TX)": "St. Mary's University (Texas)",
    #"Tennessee Southern": "",
    "Mars Hill": "Mars Hill University",
    #closed "Holy Names": "",
    "Concord": "Concord University",
    "Fairmont St": "Fairmont State University",
    "Cal State LA": "California State University, Los Angeles",
    "Texas A&M-International": "Texas A&M International University",
    "Oklahoma Christian": "Oklahoma Christian University",
    "Edinboro": "Pennsylvania Western University, Edinboro",
    "Palm Beach Atlantic": "Palm Beach Atlantic University",
    "Quincy": "Quincy University",
    "Maryville (MO)": "Maryville University of Saint Louis",
    "Gannon": "Gannon University",
    "Belmont Abbey": "Belmont Abbey College",
    "Purdue Northwest": "Purdue University Northwest",
    "McKendree": "McKendree University",
    "Bluefield State": "Bluefield State University",
    #"Olivet Nazarene": "",
    #closed "Notre Dame de Namur": "",
    #"New York Institute of Technology": "",
    #"Urbana": "",
    #closed in 2024 "Birmingham-Southern": "",
    #"Defiance": "",
    "Westminster (PA)": "Westminster College (Pennsylvania)",
    "Massachusetts-Boston": "University of Massachusetts Boston",
    "SUNY-Oneonta": "State University of New York at Oneonta",
    "Eureka": "Eureka College",
    "Purchase": "Purchase College, State University of New York",
    "UT Dallas": "University of Texas at Dallas",
    "Southwestern (TX)": "Southwestern University (Texas)",
    "SUNY Poly": "State University of New York Polytechnic Institute",
    "LeTourneau": "LeTourneau University",
    "Rhodes": "Rhodes College",
    "Emerson": "Emerson College",
    "Misericordia": "Misericordia University",
    "Rockford": "Rockford University",
    "Gallaudet": "Gallaudet University",
    "Saint Elizabeth": "Saint Elizabeth University",
    "Ferrum": "Ferrum College",
    #"Rosemont": "",
    "Texas Lutheran": "Texas Lutheran University",
    "Nazareth College": "Nazareth University",
    "Averett": "Averett University",
    "Regent": "Regent University",
    "Brevard": "Brevard College",
    "Merchant Marine Academy": "U.S. Merchant Marine Academy",
    "Thomas (ME)": "Thomas College",
    "Wisconsin-Stout": "University of Wisconsin-Stout Polytechnic",
    #"Bryn Athyn": "",
    "Pacific (OR)": "Pacific University (Oregon)",
    "Crown College": "Crown College (Minnesota)",
    "St. Thomas (TX)": "University of St. Thomas (Texas)",
    "Whittier": "",
    "Willamette": "Whittier College",
    "Johnson & Wales (RI)": "Johnson & Wales University (Providence)",
    "Johnson & Wales (NC)": "Johnson & Wales University Charlotte", #closed in 2021?
    "Heidelberg": "Heidelberg University",
    #"Benedictine (AZ)": "",
    "Anderson (IN)": "Anderson University (Indiana)",
    "Kean": "Kean University",
    "Medgar Evers": "Medgar Evers College",
    "Spalding": "Spalding University",
    "Millsaps": "Millsaps College",
    "North Park": "North Park University",
    "St. Mary’s (MD)": "St. Mary's College of Maryland",
    "Luther": "Luther College",
    "Pacific Lutheran": "Pacific Lutheran University",
    #"Northland": "",
    "SUNY-Potsdam": "State University of New York at Potsdam",
    "FDU Florham": "Fairleigh Dickinson University, Florham",
    "Bridgewater College (VA)": "",
    "Mount Saint Vincent": "University of Mount Saint Vincent",
    "Emory & Henry": "Emory & Henry University",
    "Puget Sound": "University of Puget Sound",
    "Manchester": "Manchester University",
    "Alma": "Alma College",
    "Mount St. Joseph": "Mount St. Joseph University",
    "Goucher": "Goucher College",
    "Centenary (NJ)": "Centenary University (New Jersey)",
    "Rutgers-Camden": "Rutgers, The State Univ. of New Jersey, Camden",
    "Shenandoah": "Shenandoah University",
    "Oberlin": "Oberlin College",
    "Concordia-Texas": "Concordia University Texas",
    "MIT": "Massachusetts Institute of Technology",
    "Elizabethtown": "Elizabethtown College",
    "Hartwick": "Hartwick College",
    "Cal Lutheran": "California Lutheran University",
    "Redlands": "University of Redlands",
    "Farmingdale State": "Farmingdale State College",
    "Elmira": "Elmira College",
    "Flagler": "Flagler College",
    "East Texas Baptist": "East Texas Baptist University",
    "Cornell College (IA)": "Cornell College",
    "Simpson College (IA)": "Simpson College",
    "Marymount (VA)": "Marymount University (Virginia)",
    "Thiel": "Thiel College",
    "Concordia (WI)": "Concordia University Wisconsin",
    "Illinois Wesleyan": "Illinois Wesleyan University",
    "UC Santa Cruz": "University of California, Santa Cruz",
    "Hiram": "Hiram College",
    #"Wesley": "",
    #merged into Boston College in 2021 "Pine Manor": ""
}

school_names_2020 = df_2020["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2020 = school_names_2020.apply(school_key)

matched_division_2020 = school_keys_2020.map(division_map)
update = missing_2020 & matched_division_2020.isin(["D2", "D3"])

df_2020.loc[update, "conference"] = matched_division_2020[update]
df_2020.to_csv(file_2020, index=False)

print(f"2020: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2020.loc[missing_2020 & ~update, "team"].dropna().unique()[:])

school_names_2021 = df_2021["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2021 = school_names_2021.apply(school_key)

matched_division_2021 = school_keys_2021.map(division_map)
update = missing_2021 & matched_division_2021.isin(["D2", "D3"])

df_2021.loc[update, "conference"] = matched_division_2021[update]
df_2021.to_csv(file_2021, index=False)

print(f"2021: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2021.loc[missing_2021 & ~update, "team"].dropna().unique()[:])

school_names_2022 = df_2022["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2022 = school_names_2022.apply(school_key)

matched_division_2022 = school_keys_2022.map(division_map)
update = missing_2022 & matched_division_2022.isin(["D2", "D3"])

df_2022.loc[update, "conference"] = matched_division_2022[update]
df_2022.to_csv(file_2022, index=False)

print(f"2022: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2022.loc[missing_2022 & ~update, "team"].dropna().unique()[:])

school_names_2023 = df_2023["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2023 = school_names_2023.apply(school_key)

matched_division_2023 = school_keys_2023.map(division_map)
update = missing_2023 & matched_division_2023.isin(["D2", "D3"])

df_2023.loc[update, "conference"] = matched_division_2023[update]
df_2023.to_csv(file_2023, index=False)

print(f"2023: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2023.loc[missing_2023 & ~update, "team"].dropna().unique()[:])

school_names_2024 = df_2024["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2024 = school_names_2024.apply(school_key)

matched_division_2024 = school_keys_2024.map(division_map)
update = missing_2024 & matched_division_2024.isin(["D2", "D3"])

df_2024.loc[update, "conference"] = matched_division_2024[update]
df_2024.to_csv(file_2024, index=False)

print(f"2024: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2024.loc[missing_2024 & ~update, "team"].dropna().unique()[:])

school_names_2025 = df_2025["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2025 = school_names_2025.apply(school_key)

matched_division_2025 = school_keys_2025.map(division_map)
update = missing_2025 & matched_division_2025.isin(["D2", "D3"])

df_2025.loc[update, "conference"] = matched_division_2025[update]
df_2025.to_csv(file_2025, index=False)

print(f"2025: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2025.loc[missing_2025 & ~update, "team"].dropna().unique()[:])

school_names_2026 = df_2026["team"].fillna("").astype(str).replace(name_overrides)
school_keys_2026 = school_names_2026.apply(school_key)

matched_division_2026 = school_keys_2026.map(division_map)
update = missing_2026 & matched_division_2026.isin(["D2", "D3"])

df_2026.loc[update, "conference"] = matched_division_2026[update]
df_2026.to_csv(file_2026, index=False)

print(f"2026: filled {update.sum()} missing conferences")
print("\nStill missing schools:")
print(df_2026.loc[missing_2026 & ~update, "team"].dropna().unique()[:])

2020: filled 0 missing conferences

Still missing schools:
<StringArray>
[                      'Lindenwood',              'Birmingham-Southern',
                  'Penn State-York',              'Alice Lloyd College',
                         'Defiance',           'Mid-Atlantic Christian',
           'Columbia International',                  'Trinity Baptist',
                        'Bob Jones',                 'Dallas Christian',
 ...
                        'Pikeville',                           'Wesley',
                 'Ohio-Chillicothe', 'New York Institute Of Technology',
                           'Urbana',                       'Pine Manor',
                       'Rio Grande',                     'Bethany (KS)',
             'Johnson & Wales (CO)',                      'Thomas (GA)']
Length: 150, dtype: str
2021: filled 0 missing conferences

Still missing schools:
<StringArray>
[                    'Hartford',          'Birmingham-Southern',
                   'Oglethorpe',                   'UNT Dallas',
                     'LaGrange',              'Penn State-York',
             'Framingham State',                       'Rivier',
                     'Houghton',                 'Cheyney (PA)',
 ...
  'Southwestern Oklahoma State',               'Northwood (MI)',
               'LSU Shreveport',                'Anderson (SC)',
                      'Arcadia',              'Antelope Valley',
             'St. Xavier  (IL)',            'Queens College NY',
                'Wells College', 'Indiana University Northwest']
Length: 283, dtype: str
2022: filled 0 missing conferences

Still missing schools:
<StringArray>
[                    'Hartford',          'Birmingham-Southern',
                   'Oglethorpe',                   'UNT Dallas',
                     'LaGrange',              'Penn State-York',
             'Framingham State',                       'Rivier',
                     'Houghton',                 'Cheyney (PA)',
 ...
  'Southwestern Oklahoma State',               'Northwood (MI)',
               'LSU Shreveport',                'Anderson (SC)',
                      'Arcadia',              'Antelope Valley',
             'St. Xavier  (IL)',            'Queens College NY',
                'Wells College', 'Indiana University Northwest']
Length: 283, dtype: str
2023: filled 0 missing conferences

Still missing schools:
<StringArray>
[           'Oglethorpe',            'UNT Dallas',              'LaGrange',
       'Penn State-York',      'Framingham State',              'Houghton',
   'Alice Lloyd College',        'Morris College',              'Bluffton',
              'Defiance',
 ...
 'Holy Names University',       'St. Thomas (FL)',                  'Knox',
     'Northwestern Ohio',   'Master's University',       'Glenville State',
      'Williams Baptist',  'Georgia Southwestern',       'Florida College',
        'Academy of Art']
Length: 253, dtype: str
2024: filled 0 missing conferences

Still missing schools:
<StringArray>
[                    'Hartford',          'Birmingham-Southern',
                   'Oglethorpe',                   'UNT Dallas',
                     'LaGrange',              'Penn State-York',
             'Framingham State',                       'Rivier',
                     'Houghton',                 'Cheyney (PA)',
 ...
  'Southwestern Oklahoma State',               'Northwood (MI)',
               'LSU Shreveport',                'Anderson (SC)',
                      'Arcadia',              'Antelope Valley',
             'St. Xavier  (IL)',            'Queens College NY',
                'Wells College', 'Indiana University Northwest']
Length: 283, dtype: str
2025: filled 0 missing conferences

Still missing schools:
<StringArray>
[         'IU Columbus',           'Oglethorpe',           'UNT Dallas',
             'LaGrange',      'Penn State-York',         'Old Westbury',
     'Framingham State',               'Rivier',             'Houghton',
         'Cheyney (PA)',
 ...
            'Muskingum',  'Texas A&M-Texarkana',               'Mobile',
    'Fort Valley State',     'Benedictine (AZ)',       'Eastern Oregon',
         'Colby-Sawyer',              'Bowdoin',          'Bowie State',
 'Washington Adventist']
Length: 257, dtype: str
2026: filled 0 missing conferences

Still missing schools:
<StringArray>
[             'IU Columbus',               'Oglethorpe',
               'UNT Dallas',                 'LaGrange',
          'Penn State-York',             'Old Westbury',
                   'Rivier',                 'Houghton',
             'Cheyney (PA)',      'Alice Lloyd College',
 ...
        'Bryant & Stratton',          'St. Scholastica',
             'Paul Smith'S',      'Manhattan Christian',
          'Salish Kootenai',               'Bloomfield',
        'Saint John's (MN)',      'Penn State Hazleton',
             'Baptist (Fl)', 'Bryant & Stratton (Ohio)']
Length: 277, dtype: str

## Explore data

In [ ]:
# Summarize and visualize the prepared data.

## Build models

In [ ]:
# Train baseline and candidate models.

## Evaluate models

In [ ]:
# Compare models using the chosen evaluation measures.

## Final results

In [ ]:
# Generate the final tables and figures.

## AI usage disclosure

- **AI tool/model:** [Name the tool and model, or state that no generative AI was used.]
- **Used for:** [Briefly identify the tasks.]
- **How we verified the work:** [Briefly identify the checks.]
- **Prompt(s) used:** [Paste the prompts used.]